### ISSUE TITLE
Web implementation

### ISSUE THREAD

**Issue by radog** [pchen66/panolens.js#1]
Hi! 

You script is best! I have one question: How to integrate to website with size: width:700px?

Look: http://www.panoo.eu/image/panorama-4/

Thank you :-)

**Comment by pchen66** [comment]
Thanks for sharing your work. :) I'm currently on working on fitting the viewer into a passed-in container so it will do exactly what you need by using

 `viewer = new PANOLENS.Viewer({ container: document.getElementById('ELEMENT_ID') });`

Currently, the container argument is not setup properly, so in your case these should do the trick.
```
viewer.getContainer().style.width = '700px';
viewer.widget.barElement.style.width = '700px';
viewer.getRenderer().domElement.style.width = '100%';
```
<img width="989" alt="screen shot 2016-03-01 at 7 41 36" src="https://cloud.githubusercontent.com/assets/2421225/13450000/b609927e-dfe5-11e5-96a1-3bc104eefd27.png">

**Comment by pchen66** [comment]
Done #2 
Now you can define a container with 700px width and pass it into viewer.
`viewer = new PANOLENS.Viewer({ container: document.getElementById('ELEMENT_ID') });`

**Comment by radog** [comment]
Thank you very much work fine!  I have only a one problem on just the bar element display on the bottom of site.

**Comment by pchen66** [comment]
Simply replace `viewer.widget.barElement.style.width = '920px';` to `viewer.widget.barElement.style.width = '100%';` does the trick. Next time you can pass in a container so that everything should work just fine as this one.

**Comment by radog** [comment]
Thank you very much, work perfect!!! :-)
