### ISSUE TITLE
Animation - using focus

### ISSUE THREAD

**Issue by itsbouffant** [pchen66/panolens.js#102]
I am new here. I dont know the best way to do this. But here goes.

I am enchanted with this software - and have been tweaking at a couple of files using your beginners guides and code pen examples.

I there a way of doing an animation "type thing" where upon entry to the pic, the image pans from one area to another and at a different zoom level to show up diffent interesting things.

If i create a movie using Insta360 studio I could achive this, but I would like to give it a try with Panolens. For one thing the filesize would be smaller.

Any clues?

Martin ( bouffant)

**Comment by pchen66** [comment]
This is an interesting idea. I've put it up as an example - [Panorama Storytelling](http://pchen66.github.io/Panolens/examples/panorama_storytelling.html).
