### ISSUE TITLE
[bug] zoom effect doesn`t work on android device.

### ISSUE THREAD

**Issue by tryBetter** [pchen66/panolens.js#103]
Maybe the "control" should be update. TouchEvent can not get "scale".

**Comment by huxiyu** [comment]
是的 修改了OribitControls.js ,
（1） this.zoom0 = this.object.zoom; 后增加
// android zoom bug fix: android touchEvent scale is undefined
this.zoomDistancePre;
this.zoomFlag = true;

（2）function touchstart( event ) 中 var distance = Math.sqrt( dx * dx + dy * dy );后增加
scope.zoomDistancePre = distance;

（3）function touchmove( event ) 中 var distance = Math.sqrt( dx * dx + dy * dy ); 后增加
if( distance>=scope.zoomDistancePre) {
    scope.zoomFlag = true;
} else {
    scope.zoomFlag = false;				
}
scope.zoomDistancePre = distance;

（4） 并将之后的
if ( event.scale < 1 ) {

    scope.object.fov = ( scope.object.fov < scope.maxFov ) 
				? scope.object.fov + 1
				: scope.maxFov;
				scope.object.updateProjectionMatrix();

} else if ( event.scale > 1 ) {

    scope.object.fov = ( scope.object.fov > scope.minFov ) 
				? scope.object.fov - 1
				: scope.minFov;
				scope.object.updateProjectionMatrix();

}

修改为
if ( !scope.zoomFlag ) {

	scope.object.fov = ( scope.object.fov < scope.maxFov ) 
				? scope.object.fov + 1
				: scope.maxFov;
				scope.object.updateProjectionMatrix();

} else {

				scope.object.fov = ( scope.object.fov > scope.minFov ) 
				? scope.object.fov - 1
				: scope.minFov;
				scope.object.updateProjectionMatrix();

}
