### ISSUE TITLE
I would like to open a FancyBox Picture from an OnClick function

### ISSUE THREAD

**Issue by itsbouffant** [pchen66/panolens.js#104]
I love the Pano Display, but I am not keen on the "Hover" info box. If i move away tyhe box closes.
What I am after is a way of triggering a FancyBox wibdow that has persistance until closed for close ups etc.

All of these lightbox clones use <a> as the trigger ( or seem to) is there a way of creating a custom  function?
Is there anything else out there that does this already?
Can someone help me - I am a Novice coder

Thanks in advance :)

**Comment by itsbouffant** [comment]
Necessity being the mother of invention, I Dunnit myself, after a load of swearing and coffee!
**Here's my Div..........**

< div class="desc-container" id="desc-container2" style="display:none"> < !-- This is for Panorama 2 -->
      < img src="./images/bcus.jpg" height="200" width="200"> 
      < div class="title">BCUS</div>
      < div class="text">Click HotSpot icon for Close Up</div>
    < /div>

**Here's my js**
infospot3 = new PANOLENS.Infospot( 250, "./icons/image-wh.png"  );
      infospot3.position.set( -2686.92, 380.04, -4190.96 );
      infospot3.addHoverElement( document.getElementById( 'desc-container2' ), 150 );
	  infospot3.addEventListener( 'click', function(){ $.fancybox.open( { src: './images/bcus.jpg' , caption : 'Fusce at egestas augue, a pretium ante.Duis euismod mauris ac tempus faucibus. Nullam varius ligula ut hendrerit mollis.'  }  );  } );




_FAR TOO MANY BRACKETS AND CURLY BRACES FOR MY LIKING. but it works._

**Needs this order in head**

< script src="./js/jquery-3.2.1.min.js"></script>
< script src="./js/jquery.fancybox.min.js"></script>
< script src="./js/three.min.js"></script>
< script src="./js/panolens.min.js"></script>
< link rel="stylesheet" type="text/css" href="./css/panostyle3.css">
< link rel="stylesheet" href="./css/jquery.fancybox.min.css" type="text/css" media="screen" />

**Comment by pchen66** [comment]
Looks like you solved your own question. 😄
