### ISSUE TITLE
Web GL Crashes after loading 4-5 panoramas

### ISSUE THREAD

**Issue by Jfairfield1** [pchen66/panolens.js#105]
How can I properly dispose of the panorama and infospot objects so that WebGL doesn't crash after toggling between Panoramas?

Here's what my code looks like for adding and disposing panoramas:

```
function showPanorama(key) {
    if (activePano !== key) {
        activePano = key;
        var panoSettings = config.siteList[key].pano;
        disposeAll();
        panorama = new PANOLENS.ImagePanorama('img/asset/' + key + '/Aerial.jpg');
        viewer.getControl().autoRotateSpeed = .1;
        viewer.getControl().autoRotate = true;
        viewer.getCamera().position.set(panoSettings.x, panoSettings.y, panoSettings.z);
        viewer.getControl().update();
        viewer.getCamera().fov = config.siteList[key].pano.fov;
        viewer.getCamera().updateProjectionMatrix();
        infoSpot = new PANOLENS.Infospot(panoSettings.infoSpot.size, "img/icons/amazon.png");
        infoSpot.position.set(panoSettings.infoSpot.x, panoSettings.infoSpot.y, panoSettings.infoSpot.z);
        panorama.add(infoSpot);
        viewer.add(panorama);
    }
}

function disposeAll() {
    if (panorama) {
        panorama.remove(infoSpot);
        infoSpot.dispose();
        panorama.dispose();
        viewer.remove(panorama);
        panorama = null;
        infoSpot = null;
    }
}
```

This is the error message that comes up when Web GL crashes:

![image](https://user-images.githubusercontent.com/13153086/31506603-b726d762-af2c-11e7-869f-91dcb31d1984.png)

It should also be mentioned that my file size ranges from 4-6mb per Panorama

The files are 15000 x 7500 px

I absolutely love the library.  It's very very helpful.  Thanks in advance for any help on this issue.

**Comment by Jfairfield1** [comment]
I think the file size is likely my issue....  I compressed and resized the images down to 2000 x 1000 and it seems to work.  Some of the detail is lost from the original image though.  Can you recommend a maximum file size to use with PANOLENS.js?  or is there a preferred method for reducing file size that maintains quality?

**Comment by Webcretaire** [comment]
I have the same problem, if you look into the console it says that WebGL runs out of memory, so definitely it seems like displaying too many big files fills up the memory and en up in a crash. I don't know if the problem is in Panolens, Threejs or WebGL though, I don't know which one should free the memory or if there is a solution. If there is not I'm also interested in knowing which size is recommended for the pictures

**Comment by Jfairfield1** [comment]
Even after making my file sizes considerably smaller, it crashes after a while.  Seems like maybe a garbage collection issue or something.

**Comment by huxiyu** [comment]
纹理绑定了，没有解绑，导致GPU显存爆炸了，尤其是手机使用时，直接闪退。所以进行纹理解绑就可以了。 
比如PANOLENS.CubePanorama
1. 修改源代码，我这里通过定义 this.texture 存放纹理句柄。

    PANOLENS.CubePanorama = function ( images, edgeLength ){

        var shader, geometry, material;

        this.images = images || [];

        // texture handle
        this.texture;

然后在获取texture，如下：

    /**
    * Load 6 images and bind listeners
    */
    PANOLENS.CubePanorama.prototype.load = function () {

        this.texture = PANOLENS.Utils.CubeTextureLoader.load( 	

            this.images,

	    this.onLoad.bind( this ), 
	    this.onProgress.bind( this ), 
	    this.onError.bind( this ) 

	 );

    };


2. 在你的项目中，使用 threejs的方法 dispose() 释放GPU内存，如下

    var panorama = new PANOLENS.CubePanorama(imgArr);
    
    panorama.texture.dispose();

**Comment by Jfairfield1** [comment]
Thanks @huxiyu, however I'm not sure I understand how the code you posted is any different than the current repo code.  If someone is able to get this to work and could explain in English I would very much appreciate.

**Comment by pchen66** [comment]
I've updated the texture memory releasing and cleanup caching mechanism under the [dev](https://raw.githubusercontent.com/pchen66/panolens.js/dev/build/panolens.min.js) branch. You can test this [Memory Leaking Test Example](http://pchen66.github.io/Panolens/examples/panorama_memoryleak_test.html) to see if it's still reproducible on your end. 

I ran this >30min and memory curve stays at a reasonable level. In the example, 5 images (from 15000x7500 to 4000x2000) with size ranging from 26MB to 3.5MB are used. Let us know if the you still hit the snag.

**Comment by Jfairfield1** [comment]
Unfortunately, the problem still exists when I run your example on my machine.  Web GL hits a snag after a while.

**Comment by pchen66** [comment]
I tried again with 100ms still unable to reproduce. Looks like something else causes the issue. What's your running environment including browser (with version), os, ram size?

**Comment by Jfairfield1** [comment]
Running on Windows 10 in Google Chrome 65 with 8 GB of RAM
