### ISSUE TITLE
Non minified version is a mirror image

### ISSUE THREAD

**Issue by Jfairfield1** [pchen66/panolens.js#106]
Panorama is a mirror image if I include the non-minified version of the library.  The minified version works as expected.

**Comment by NFGman** [comment]
The images are reversed right-to-left no matter which version I use.

**Comment by ricmob** [comment]
I got it to work with the LittlePlanet by modifying the three.js file.
In three.min.js, change flipY=!0 to flipY=!1 (from true to false).

Problem is, it now starts in inverted mode. I'll raise a new issue for this.

**Comment by melovje** [comment]
Now is not a mirror but it translates a little bit to the right
