### ISSUE TITLE
Zoom direction

### ISSUE THREAD

**Issue by garymould** [pchen66/panolens.js#108]
Is there any way to reverse the mousewheel zoom direction?

99% of interfaces zoom in when you move the mouse wheel towards it. The current method seems unintuitive to me.

**Comment by Jfairfield1** [comment]
I was able to modify this myself.  Just change the greater than and less than operators in the 'onMouseWheel' function.  like this:

```
if (delta < 0) {
    scope.object.fov = (scope.object.fov < scope.maxFov) ? scope.object.fov + 1 : scope.maxFov;
    scope.object.updateProjectionMatrix();
}  else if (delta > 0) {
    scope.object.fov = (scope.object.fov > scope.minFov) ? scope.object.fov - 1 : scope.minFov;
    scope.object.updateProjectionMatrix();
}
```

**Comment by garymould** [comment]
Thanks @Jfairfield1, I'll give it a try.

A simple option for zoom direction would be brilliant.

**Comment by NFGman** [comment]
This is weirdly common with 360-degree viewers, I've tried several in the last few days and they're all backwards.  Thanks for the fix, @Jfairfield1

**Comment by Jfairfield1** [comment]
The only signs you need to change are the > and < in the if statements.  Just try copying my snippet in and see if it works.

**Comment by NFGman** [comment]
OK, the issue is with the LittlePlanet projection.  Changing those symbols or copying your code has the desired result in other projections, but it's still backwards in LittlePlanet.

**Comment by ricmob** [comment]
I got it to work with the LittlePlanet by modifying the three.js file.
In three.min.js, change **flipY=!0** to **flipY=!1** (from true to false)
