### ISSUE TITLE
Stereographic without LittlePlanet?

### ISSUE THREAD

**Issue by NFGman** [pchen66/panolens.js#109]
For several reasons I prefer the stereographic projection with all its curves and fisheye appearance over the default rectilinear projection.  I'd very much like to use the standard Panorama viewer, without the fast and swoopy Little Planet extreme POV.  

Which might just be LittlePlanet mode without being able to pass the top and bottom poles.  Once you've swirled past the poles once or twice the image can become confusing and it's difficult to re-level the horizon.

Is there a way to do this?

**Comment by pchen66** [comment]
The little planet panorama inherits from image panorama so it shares similar methods and attributes. Do you have an example to illustrate "use the standard Panorama viewer, without the fast and swoopy Little Planet extreme POV"?

**Comment by NFGman** [comment]
Panning with the mouse is much faster with the little planet projection, and vertical movement does not stop at the poles like the normal panorama.  As a result, the viewer can quickly become disoriented, and the image may become inverted or tilted at extreme angles.

What I'm hoping for is the same controls and limits as the normal projection, but with the stereographic curves.

**Comment by NFGman** [comment]
Can anyone help with the littleplanet controls?  Basically, I want this script to act like [Ricoh's Theta viewer](https://theta360.com/en/about/application/pc.html).  There are three changes in total, but I've been beating my head against this script on and off for months and I can't figure out what to change (I am not good with javascript).

1. Slow the movement down, to the same speed as ImagePanorama (or, make it adjustable?)
2. Make horizontal user scrolling parallel to the image horizon, instead of parallel to the screen
3. Do not allow the viewer to move vertically past the poles.  By that, I mean: when you scroll the viewer to vertical, it can't go -past- vertical, and make the scene upside down.

I love the littleplanet stereographic projection, but I want the regular panorama controls.

**Comment by pchen66** [comment]
In Ricoh's Theta viewer, it looks like spherical projection. Are you looking for similar to this example? [External View](https://codepen.io/pchen66/full/zWYRxY/) It's still regular orbit control.

**Comment by NFGman** [comment]
I think when you say 'spherical' it's exactly the same as '[stereographic](https://en.wikipedia.org/wiki/Stereographic_projection#Photography)'.  

The LittlePlanet projection is exactly what I want, but with locked poles, so the sphere spins like your 'External View' link, and like the Ricoh Theta app.  

Does that make any more sense?  =)
