### ISSUE TITLE
garbage collection/destroy method

### ISSUE THREAD

**Issue by hvbe** [pchen66/panolens.js#11]
hi there

great plugin! works pretty well and is one of the most high performance pano plugins out there!
i am using it in conjunction with the magnific popup plugin and encountered some problems.

in order to have multiple pano views and only load three.js and panolens.js when needed i create new pano instances when the user opens a popup. i encountered pretty significant performance issues when creating multiple instances of the panolens plugin. i somehow doubt that the plugin was intended to be used this way. 

is there a destroy method which detaches all the listeners and does all the carbage collection? or is this maybe an issue with three.js?

**Comment by pchen66** [comment]
hey! currently there's no disposal function to clear the scene, but this is a good suggestion. I'm currently working on disposing scene object method, which might help regarding the performance in general. In your case, I would recommend keep the `viewer` running and dynamically creating `panorama` each time  a user clicks on magnific popup image so it will run smoothly.

**Comment by hvbe** [comment]
good idea! thanks for the suggestion!

**Comment by pchen66** [comment]
Viewer and Panorama now has `dispose` methods for clean up. 7d30edda6bc412b4246260d6a9fe14b07ed2b415 
Also added an [simple gallery example](http://pchen66.github.io/Panolens/examples/panorama_simple_gallery.html) to demonstrate a possible scenario on dynamically creating and disposing panoramas. I didn't notice any significant performance impact. Let me know if you still hitting performance issue in this example.

**Comment by pchen66** [comment]
#12
