### ISSUE TITLE
Panolens usage in iframe on iOS => no gyro sensor anymore

### ISSUE THREAD

**Issue by donblaauw** [pchen66/panolens.js#110]
Also I cant drag the view in horizontal ways..only vertical..Android works fine, Desktop works fine..
What's so special??  This is plain weird.

Try it:
http://rondkijker.com/

(the domain forwards to the panolens page within an iframe construction.

**Comment by pchen66** [comment]
Apple blocks this cross-origin access.
https://bugs.webkit.org/show_bug.cgi?id=150072
https://bugs.webkit.org/show_bug.cgi?id=152299

<img width="998" alt="screen shot 2017-12-18 at 4 27 22 pm" src="https://user-images.githubusercontent.com/2421225/34135543-235bc104-e416-11e7-8d5c-68e589e1d65a.png">

The workaround is to host your page within the same domain.
