### ISSUE TITLE
Is there any way to create a customized info spot?

### ISSUE THREAD

**Issue by liujerry1992** [pchen66/panolens.js#111]
Hi,

Is there any way to customize animation, style of info spot? If you author see this, please help me about this question. I'm really lost, thanks!

**Comment by pchen66** [comment]
Hi,

Yes it is. You can disable default animation by passing `false` as the third parameter when creating a new infospot.
```
new PANOLENS.Infospot( 300, YOUR_IMAGE_URL, false );
```
Then you can attach event listener to `hoverenter` and `hoverleave` to overwrite default behaviors.

Take a look at this [Custom Infospot](https://codepen.io/pchen66/pen/dRYNNG) example to see side by side comparison.

**Comment by donblaauw** [comment]
Hey Ray.
do you have some more examples where the panorama video is used for mobile usage?
and did you make interface control buttons to be “gazed” at to activate (e.g. play/pause, stop, total Rewind,fastrewind(1sec), fastforward (10sec) and such?)


Met vriendelijke groet,

Don Blaauw

----------------------------------------------------

Don Blaauw
Creative Director of playful Interactives
studio No More Mondays 

Werkwarenhuis
Tramkade 20G,
5211 VB  's-Hertogenbosch

Tel:        +31 (6) 24581166 
Mail:      don@nomomo.nl <mailto:don@nomomo.nl> 
Website: www.nomomo.nl <http://www.nomomo.nl/> 
Twitter:   twitter.com/donnomomo <https://twitter.com/donnomomo>
LinkedIn: www.linkedin.com/in/donblaauw <http://www.linkedin.com/in/donblaauw> 



No More Mondays
'bringing the FUN back into function"

Kids Love Cards
‘Transmedial storytelling, using fun to educate. ”
Website: www.kidslovecards.nl <http://www.kidslovecards.nl/> 

VRhalen.nl
‘The story is all around you!”
Website: www.vrhalen.nl <http://www.vrhalen.nl/> 

----------------------------------------------------










On Dec 21, 2017, at 23:43, Ray Chen <notifications@github.com> wrote:

Hi,

Yes it is. You can disable default animation by passing false as the third parameter when creating a new infospot.

new PANOLENS.Infospot( 300, YOUR_IMAGE_URL, false );
Then you can attach event listener to hoverenter and hoverleave to overwrite default behaviors.

Take a look at this Custom Infospot <https://codepen.io/pchen66/pen/dRYNNG> example to see side by side comparison.

**Comment by ismaildkc** [comment]
Can't I use an html object instead of an image?
