### ISSUE TITLE
infospot weird offest

### ISSUE THREAD

**Issue by richardegil** [pchen66/panolens.js#112]
Trying to add an infospot to a panolens canvas, but the infospot seems to have a weird offset. Here is a gif of what is happening and the snippet of code.

Gif:
http://d.pr/i/fkld8K

Code: (github was causing weird formatting)
http://d.pr/n/e4VZBK

**Comment by richardegil** [comment]
Any help? Please?!?!?

**Comment by pchen66** [comment]
Looks like it relates to #107 . Can you try again with [dev](https://raw.githubusercontent.com/pchen66/panolens.js/dev/build/panolens.min.js) build and let us know if that fixes the issue?

**Comment by richardegil** [comment]
I tried the dev branch and now I can't get the panorama image to show up. Did any of the setup change in the dev version?

Thanks for the help!

**Comment by sonic40** [comment]
I think the problem came from latest "THREE.JS" version, 

try to downgrade your "THREE.JS" into version 93.

Cheers,
Sonic40
