### ISSUE TITLE
Is it possible to drag and drop an infospot?

### ISSUE THREAD

**Issue by sujanneeraj** [pchen66/panolens.js#114]
Hello, is it possible to drag and drop an infospot at a specific position in the scene?

**Comment by donblaauw** [comment]
This would indeed be in nice and feature I would like to use :-)

**Comment by nrj127** [comment]
Hi,

I tried to use THREE.DragControls to drag my infospot. I can manage to drag it but I am not able to drag it very smoothly and as soon as the infospot goes further away from the camera, I am unable to drag it. 
Below is a code snippet of what I did.

`var panorama, viewer, infospot, dragcontrols;
panorama = new PANOLENS.ImagePanorama('kitchen.JPG');

infospot = new PANOLENS.Infospot(600);
infospot.position.set(1000, 100, -2000);
panorama.add(infospot);



viewer = new PANOLENS.Viewer();
viewer.add(panorama);

var objects = [];
objects.push(infospot);
dragcontrols = new THREE.DragControls(objects, viewer.camera, viewer.renderer.domElement);
dragcontrols.addEventListener('dragstart', function(event) {
    console.log("drag started");
    viewer.control.enabled = false;
})

dragcontrols.addEventListener('dragend', function(event) {
    console.log("drag stopped");
    viewer.control.enabled = true;
});
`

**Comment by urfielahi** [comment]
Hi,

My requirement is to drag and drop few Panolens Infospots and store the new infospot position. I used THREE.DragControls to achieve this. Some of the infospots are responding to the drag event and are moving as expected. Few are not moving at all. The infospots which move are moving opposite to the dragging direction. Any update on this?

**Comment by silqwer** [comment]
ㅇ

**Comment by mehulcse** [comment]
@urfielahi 
Hey did you find any solution for the reverse dragging? I'm also facing the same issue.
