### ISSUE TITLE
Upload panoramic image

### ISSUE THREAD

**Issue by sujanneeraj** [pchen66/panolens.js#116]
I have an input field in order to upload my Panaromic image. On upload how can I set the image as a parameter to the PANOLENS.Imagepanaroma (). I am using the filereader API to read the image as a data URL. Thanks for the support.

**Comment by pchen66** [comment]
Check this [File Upload](https://codepen.io/pchen66/pen/qKOwVm) example. To keep it reusable, create an image panorama and upload the texture whenever data is ready.
