### ISSUE TITLE
Animated Hotspots

### ISSUE THREAD

**Issue by rsjackson101** [pchen66/panolens.js#121]
Hi - Please can someone advise if you can add an animated gif as a hotspot?   I'm able to create custom hotspots, but only as PNGs or JPGs.   When I try and use an animated gif it doesn't seem to load.

Thanks.

**Comment by barnnnn** [comment]
Hey! I'm interested too! Any ideas?

**Comment by yoyomule** [comment]
Has the problem been solved?

**Comment by ahmedkandil2015** [comment]
any update?

**Comment by ramanoraglobal-lab** [comment]
Hello, Whats the solution for animated hotpsots?
