### ISSUE TITLE
Hotspots not clickable when no fullscreen

### ISSUE THREAD

**Issue by mmaarten** [pchen66/panolens.js#124]
Hi,

Is it possible to also interact with the hotspots when fullscreen is not active?

My container element is included inside the page content and not the body.

Thank you and regards,

Maarten

**Comment by claytonrothschild** [comment]
I am unable to reproduce your issue. For instance, in the below example one can click and hover over the infospot when the container element is set as a div within body: https://codepen.io/pchen66/pen/gMmggW

**Comment by SergiuMaja** [comment]
Hi.
I am able to reproduce the problem. An extra detail I've noticed is that if I go fullscreen and then exit the fullscreen it will work also.
