### ISSUE TITLE
is there a way to get the video timeline ?

### ISSUE THREAD

**Issue by contactzed8** [pchen66/panolens.js#125]
I'd like to launch event on specific point of the timeline.

Great job !!!

**Comment by contactzed8** [comment]
Hi

thanks a lot for your quick response but it does not work… I’m trying to find a solution…

Gil

**Comment by pchen66** [comment]
In the [Video Panorama](http://pchen66.github.io/Panolens/examples/panorama_video.html) example, if you open the console like below and type `panorama.videoElement.currentTime` you can see the current time of video that's being played. 

Can you elaborate more on what doesn't work and what's expected result?

<img width="1433" alt="screen shot 2018-03-03 at 2 39 05 pm" src="https://user-images.githubusercontent.com/2421225/36940081-2d3fd3f2-1ef1-11e8-9ce6-4af4f9871aaf.png">

**Comment by contactzed8** [comment]
OK I see… Excuse me I’m not a developper. In fact, I tried to access current time to launch js function at a specific time.
I tried in js something like :

panorama = new PANOLENS.VideoPanorama( "images/NetheosVidLaptop.mp4",  { autoplay: true, loop: false, muted: false } );

 viewer = new PANOLENS.Viewer( { 
    (…)
  } );

var current = panorama.videoElement.currentTime;

function blablabla () {
…
}

if(current> 10) {
	blabla();
}

I guess it’s not as simple as that :-)

**Comment by contactzed8** [comment]
Allright I finally found how to do. Thanks a lot for your help.
Your Panolens is wonderful, gonna contribute.

Gil

**Comment by donblaauw** [comment]
do you have your own  working video example to show online?
do we have load balancing at all?
