### ISSUE TITLE
[Support] Disable visibility toggle of infospots on click

### ISSUE THREAD

**Issue by JannikHv** [pchen66/panolens.js#128]
When clicking on a panorama the default behaviour is that the visibility of all infospots get toggled. How do I prevent this from happening?

EDIT: I was only able to avoid this behaviour by reassigning/overriding the prototype function.

```javascript
PANOLENS.Panorama.prototype.toggleInfospotVisibility = function() {};
```

**Comment by garymould** [comment]
It's in the docs: https://github.com/pchen66/panolens.js#panolensviewer-configuration

```
viewer = new PANOLENS.Viewer({
	autoHideInfospot: false	// Auto hide infospots
});
```

**Comment by JannikHv** [comment]
How could I have missed that... Thanks a bunch!
