### ISSUE TITLE
How to make the library importable?

### ISSUE THREAD

**Issue by mudin** [pchen66/panolens.js#130]
Hello, thank you for the awesome work!
This is not library issue, just need a help.

I am trying to integrate this library to VueJS.
I added this to my project using `npm install 'panolens' --save`
and called it in my component:
`import THREE from 'three'`
`import PanoLens from 'panolens.js'`

there is reference error: `'THREE is not defined'`

Is there way to support this kinda cases?

**Comment by gsabater** [comment]
Create a new file called `Panolens.js` with the contents of https://github.com/pchen66/panolens.js/blob/master/build/panolens.js

In that file you must import threejs at the beggining
`import * as THREE from 'three';`

and then at the end of the file, 
```
export default {
    TWEEN,
    PANOLENS
};
`

On the page you want to use panolens, import the Panolens file you created:
`import Panolens from './../lib/Panolens'; `

and  create both globals 
```
let TWEEN    = Panolens.TWEEN;
let PANOLENS = Panolens.PANOLENS;
`

This way you can use `panorama = new PANOLENS.ImagePanorama('/dist/field.jpg');`

**Comment by imudin** [comment]
@gsabater  Thank you very much for nice explanation! it works well.
Only thing is when panolens updates, I will have to update my module.

**Comment by marumori-c** [comment]
Sir help
I follow your instruction but i got error like this:

Uncaught TypeError: Cannot read properties of undefined (reading 'EventDispatcher')

Please help me

**Comment by dalelotts** [comment]
Same error with remix.js

**Comment by blitzve0** [comment]
window is not defined in Next JS also

**Comment by sharak** [comment]
I'm also have "window is not defined" error in NextJS.

As workaround you can import dynamically the library:
```		
import('panolens').then(({ImagePanorama, Viewer}) => {
    const panorama = new ImagePanorama(image)
    const view = new Viewer()
    view.add(panorama)
})
```

**Comment by omegastripes** [comment]
```
import * as THREE from 'three'
import * as PANOLENS from 'panolens/build/panolens.module'
```
