### ISSUE TITLE
Set starting position of panorama or LittlePlanet

### ISSUE THREAD

**Issue by ricmob** [pchen66/panolens.js#131]
Thanks Ray, for the great work!

This is not an issue, but a request to anyone for help.

I modified the three.js file in order to prevent images showing in mirror-image.
In three.min.js, I changed flipY=!0 to flipY=!1.

The problem is, now LittlePlanets start in rabbit-hole (inverted) mode. How do I set the starting position of the camera or viewer? I've tried 
panorama.rotation and viewer.tweenControlCenter:
https://codepen.io/ricmo/pen/qoXjzj

**Comment by Dok11** [comment]
I has similar issue — I was needed setup position by y axis wich was decided by this code:
```js
const control = viewer.getControl();
control.panUp(-0.3); // move camera up
```

**Comment by ricmob** [comment]
Thanks for the code @Dok11. The following are also useful
`control.panLeft(-0.5); 
control.dollyOut(5); `
They work well with 
`panorama = new PANOLENS.ImagePanorama( `

but unfortunately, they seem to have no effect on 
`panorama = new PANOLENS.ImageLittlePlanet(`

**Comment by flyandi** [comment]
Marking this as stale as it's older than 6 months. Subject to be closed.
