### ISSUE TITLE
Custom Move Buttons and Cursors

### ISSUE THREAD

**Issue by deep42** [pchen66/panolens.js#132]
Hello,

I am trying to add 4 custom buttons that will replicate the arrow keys of the keyboard, however I do not know what method to call to get the camera to move left/ right/ etc. Can you please help?

I figured out how to add custom buttons in the control bar, how to set autorotate and zoom.
For zoom, it was fairly easy:
```
var currentZoom = viewer.camera.fov;
var newZoom = currentZoom + 10;
if(newZoom > 120) newZoom = 120;
viewer.setCameraFov(newZoom);
```

Also, is there a way to set a cursor for the panorama itself (.panolens-container / canvas) and a different one for the infospots (ex: move and pointer)?

Thank you.

**Comment by deep42** [comment]
OK, so I figured out the command:

`viewer.OrbitControls.rotateLeft(-120);`

However, how do I get to it to keep track of the momentum?

Thank you.

**Comment by claytonrothschild** [comment]
Hi @deep42, did you ever iterate on this? Would be grateful if you shared your final solution.

**Comment by claytonrothschild** [comment]
So we know we can move the camera using the command above:

`viewer.OrbitControls.rotateLeft(-120);`

However, the camera jumps - there is no transition. It is not smooth. To get smooth, proper transitions to new camera views, which can be hooked up to custom move buttons, implement the following:

Viewer.js has a method called tweenControlCenter.

This method can receive a THREE.Vector3 object and smooth transition the camera using Tween.JS.

for example,
`viewer.tweenControlCenter(  new THREE.Vector3(100.66, -50.56, -150.44), 2000 )`

So, one might accomplish custom move methods by first getting the current world position, and then offsetting off this position to a new position:

ie,
```
function getCurrentPosition(){
var intersects, point, panoramaWorldPosition, outputPosition;

		intersects = viewer.raycaster.intersectObject( viewer.panorama, true );

		if ( intersects.length > 0 ) {

			point = intersects[0].point;
			panoramaWorldPosition = viewer.panorama.getWorldPosition();

			// Panorama is scaled -1 on X axis
			outputPosition = new THREE.Vector3(
				-(point.x - panoramaWorldPosition.x).toFixed(2),
				(point.y - panoramaWorldPosition.y).toFixed(2),
				(point.z - panoramaWorldPosition.z).toFixed(2)
			);}

			return outputPosition
		}

viewer.tweenControlCenter(  new THREE.Vector3(getCurrentPosition().x - 100, getCurrentPosition().y - 100, getCurrentPosition().z - 100), 2000 )

```

Tieing it all together, your methods might look like this, etc.:

```
function moveLeft(){
	var currentPosition = getCurrentPosition();
	viewer.tweenControlCenter(  new THREE.Vector3(getCurrentPosition().x - 100, 
		getCurrentPosition().y, getCurrentPosition().z), 2000 )
}

function moveRight(){
	var currentPosition = getCurrentPosition();
	viewer.tweenControlCenter(  new THREE.Vector3(getCurrentPosition().x + 100, 
		getCurrentPosition().y, getCurrentPosition().z), 2000 )
}

function moveDown(){
	var currentPosition = getCurrentPosition();
	viewer.tweenControlCenter(  new THREE.Vector3(getCurrentPosition().x, 
		getCurrentPosition().y - 100, getCurrentPosition().z), 2000 )
}
```

**Comment by deep42** [comment]
Looks interesting, I'll give it a try. Thank you.

**Comment by deep42** [comment]
Unfortunately I didn't figure it out.
Somehow all the functions rotate right regardless of the +/- signs.
I also had to put parseFloat() for outputPosition, because y and z came out as strings.
I will try again after my holiday.
Thank you.

**Comment by deep42** [comment]
Maybe I am retarded, but I just can't figure it out.

The getCurrentPosition() function above is nearly identical to PANOLENS.Viewer.prototype.outputInfospotPosition (which outputs cursor position in the console), so it should be fairly simple, however it returns completely different coordinates than the one you can "measure" with your mouse.
Also, if you execute moveLeft() for example twice, the second time nothing happens, as if the (new) current position does not update. I tried using -200, -500, -1000: with every iteration, the camera pans less and less.

Does anyone have any ideas? Thank you.

**Comment by deep42** [comment]
Anyone?

**Comment by webfalcon** [comment]
Hi There. You can rotate with Tween.js and this function to have a great animation rotation!
First please link Tween.js to your project.
`
var ROTATION_POSITION = 0.008;

function RotateLeftRigth(param /* 0 - right, 1 - left */){
    let go = ROTATION_POSITION;
    let back = - ROTATION_POSITION;
    let pos  = param < 1 ? go : back;
    let easing = {val : pos};
    let tween = new TWEEN.Tween(easing) 
        .to({val: 0}, ROTATION_SPEED) 
        .easing(TWEEN.Easing.Quadratic.InOut) 
        .onUpdate(function() { 
            viewer.OrbitControls.rotateLeft(easing.val)
    }).start();
}`

So call this function on your Left/Right arrow buttons, and give 0 or 1 parameter.

For up and down animated rotation use this function:

`
function rotateUpDown(param){
    let go = ROTATION_POSITION;
    let back = -ROTATION_POSITION;
    let pos  = param < 1 ? go : back;
    let easing = {val : pos};
    let tween = new TWEEN.Tween(easing) 
        .to({val: 0}, ROTATION_SPEED) 
        .easing(TWEEN.Easing.Quadratic.InOut) 
        .onUpdate(function() { 
            viewer.OrbitControls.rotateUp(easing.val)
    }).start();
}
`

Thanks

**Comment by deep42** [comment]
Thanks a lot. Works great.
I set

```
var ROTATION_POSITION = 0.2;
var ROTATION_SPEED = 150;
```

to get a smooth transition.

Have a nice day.

**Comment by bharath-exads** [comment]
I would love if there is a codepen example of this implementation.

I am trying to build a custom key for moving left, right, up and down. And not using raycaster to obtain the position of mouse click

**Comment by deep42** [comment]
Not codepen, but [this](http://bnr.bluecactus.ro/360/?en) is the implementation I was working on

**Comment by claytonrothschild** [comment]
@deep42 awesome implementation. Very impressive implementation of this library.

**Comment by deep42** [comment]
Thank you
