### ISSUE TITLE
Android zoom issue in Revision 9 and to increase zoom speed (Pinch in or out)

### ISSUE THREAD

**Issue by vip20** [pchen66/panolens.js#136]
First I would like to appreciate the developer for such a beautiful api.
**Query A:**
I tried http://pchen66.github.io/Panolens/examples/panorama_image.html and the zoom worked perfectly in Android, panolens.js (Revision 10-dev) but the panolens.js in github (revision 9) which doesn't have zoom functionality for Android.
**Query B**
Also is there a way to increase the zoom speed in the code? As I need to pinch in/out too many times to get the area in view. 
Please help

**Comment by PabbleDabble** [comment]
I have been digging in to this a bit also (and have to agree this api is pretty incredible!).  

I'm looking in to 'addZoomDelta' within 'onMouseMove'.  You can see "case 2" in the latter is the pinch.  I'll update if I can find anything more.
