### ISSUE TITLE
Compass mode

### ISSUE THREAD

**Issue by shou034** [pchen66/panolens.js#138]
For the 360 viewer: is it also possible to make use of a compass mode?

For instance:

We have a 360 image with a reconstruction of our city square 500 years ago. It would be really nice if the user can stand on the square and point the device on a certain building and that the image automatically turns in the right direction. This would mean that directions like north, south, west, and east are always 'fixed'.

At this moment, the user has to set the image in the right direction 'manually' first.

**Comment by ricmob** [comment]
It can be done, if you can work out how to incorporate https://ai.github.io/compass.js/

**Comment by sonic40** [comment]
This the "simple" way :
1. you need JQueryRotate plugin, can be found at http://jqueryrotate.com/
2. Small transparent (.png) picture of compass, let say in 64 x 64 pixel dimension

How to make it run ?

In your top or head section html page, add this :

`<script src="js/jQueryRotate.js" type="text/javascript" language="javascript"></script>`

on head style section, add this :

```
#compassplace {
	position:absolute;
	z-index:200!important; 
	height:64px!important; 
	width:64px!important; 
	bottom:50px!important; 
	left:5px!important;
}
```

on the body html section, you can add this :

```
<div id="compassplace">
	<img id="compass" src="your_compas.png" >
</div>
```

Now, the trigger event on compass rotate, can be adding into your javascript bottom section or at the last line :

```
var northpos = 0;

viewer.getControl().addEventListener('change',function() {
	var y = viewer.getCamera().rotation.y;
	if (y<0) dy = THREE.Math.radToDeg(y + (2 * Math.PI));
	else dy = THREE.Math.radToDeg(y);
	dy = Math.round(dy) - northpos;
	$("#compass").rotate(dy);
});
```

That's it :)

Cheers,
Sonic40
