### ISSUE TITLE
Enable cardboard mode, deviceorientationcontrol with functions

### ISSUE THREAD

**Issue by aramvr** [pchen66/panolens.js#139]
Is there any function I can use to enable cardboard mode and another controls with calling a function. I designed a custom cardboard mode and fullscreen button so I need to use the functions with calling the functions.

Thanks

**Comment by claytonrothschild** [comment]
Check out the control externally example: https://codepen.io/pchen66/pen/dmmGKM. 

You can call the orientation controls from any external function easily by calling `enableControl()` and `enableEffect()` (and `disableEffect()`)

Examples: `viewer.enableControl( PANOLENS.Controls.ORBIT )` for controls and `viewer.enableEffect( PANOLENS.Modes.CARDBOARD );` for presentation.

**Comment by ktrendy** [comment]
How can we create custom fullscreen button?
