### ISSUE TITLE
PANOLENS.ImageLittlePlanet shows a black screen only

### ISSUE THREAD

**Issue by temperatio** [pchen66/panolens.js#143]
I've been testing the library and it works ok for PANOLENS.ImagePanorama, but when I try to use PANOLENS.ImageLittlePlanet the result is a black screen.

Here it is the code I use:

```html
<!doctype html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width, shrink-to-fit=no">
    <meta charset="utf-8">
    <style>
        html, body {
            margin: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            background-color: #000;
        }
    </style>
</head>
<body>
<script src="js/three/three.min.js"></script>
<script src="js/panolens/panolens.min.js"></script>
<script>
    var panorama, viewer;
    viewer = new PANOLENS.Viewer( {
        output: 'console'
    } );
    panorama = new PANOLENS.ImageLittlePlanet('https://fotoweb.cyberdespacio.org/wp-content/uploads/2018/06/shanghai.jpg');
    viewer.add( panorama );
</script>
</body>
``` 
Here you can view it running: [https://fotoweb.cyberdespacio.org/wp-content/plugins/d2l-spherical-viewer/iframe.php?img=https://fotoweb.cyberdespacio.org/wp-content/uploads/2018/06/shanghai.jpg&format=planet](https://fotoweb.cyberdespacio.org/wp-content/plugins/d2l-spherical-viewer/iframe.php?img=https://fotoweb.cyberdespacio.org/wp-content/uploads/2018/06/shanghai.jpg&format=planet)

**Comment by avirtum** [comment]
Try to set the parameter "side" = THREE.DoubleSide inside the createMaterial method (see code below)

```
PANOLENS.LittlePlanet.prototype.createMaterial = function ( size )  {
	var uniforms = PANOLENS.StereographicShader.uniforms;
	uniforms.zoom.value = size;
	return new THREE.ShaderMaterial( {
		uniforms: uniforms,
		vertexShader: PANOLENS.StereographicShader.vertexShader,
		fragmentShader: PANOLENS.StereographicShader.fragmentShader,
		side: THREE.DoubleSide
	} );
};
```

**Comment by pchen66** [comment]
@avirtum solution was correct. The root cause of this is three.js change the default behavior a while ago. The link was using three.js r89, if you switch to latest r99 it's working as expected.

Here's the demo link
https://codepen.io/pchen66/full/gENery
