### ISSUE TITLE
How to listen for 'panolens-dual-eye-effect' event?

### ISSUE THREAD

**Issue by claytonrothschild** [pchen66/panolens.js#145]
Hi,

I'm having trouble listening for the 'panolens-dual-eye-effect' event. What object should I attach my listener to? I am attached it to `viewer` but I do not see any event when I `monitorEvents` in dev tools.

This is what I have so far (the below code would hide a sidebar):

``viewer.addEventListener( 'panolens-dual-eye-effect', function() {
              var sidebar = document.getElementById('sidenav');
              sidebar.classList.add( 'hide' );
              sidebar.style.display = 'none';
}, true );``

**Comment by sonic40** [comment]
try "viewer.panorama.addEventListener" like this :

```
viewer.panorama.addEventListener("panolens-dual-eye-effect", function() {
	switch (viewer.mode) {
	case 2 : alert('Cardboard');
		 break;
	case 3 : alert('Stereoscopic');
		 break;
	}	
});
```
