### ISSUE TITLE
Oculus Go and panolens. Good match?

### ISSUE THREAD

**Issue by donblaauw** [pchen66/panolens.js#147]
It seems the oculus Go browser doesn't like my version of panolens. The gyro didn't pick up the VR mode. Does Anyone experience the same?

**Comment by donblaauw** [comment]
This could be a little problem.. I saw  VR makers doing it with A-Frame.. Is he Panolens dev group fast enough to keep up the pace?

**Comment by crzdg** [comment]
We are also facing a project to use Oculus Go and panolens. Following question popped up while discussing the use of it. How are we able to get a full VR experience on the glasses. We found some projects using WebVR and ThreeJS, inspecting the panolens project it should be possible to implementit with the WebVR.js. Also some users stated the use of a more capable browser than the Go Browser, like Firefox Reality. We're updating as soon we get some results, but it would be very helpful if a developer or user could make a statement towards it.

Thanks in advance,

Reto

**Comment by crzdg** [comment]
No results here! Project is actual given external as we can't do it with panolens. Didn't consider A-Frame as we don't have time to learn an new Framework.

**Comment by sonic40** [comment]
> It seems the oculus Go browser doesn't like my version of panolens. The gyro didn't pick up the VR mode. Does Anyone experience the same?

For testing your gyro sensor on Oculus Go browser you can using test it by opening this :

https://threejs.org/examples/misc_controls_deviceorientation.html

This is the basic test for panolens, because panolens need "three.js" for working with WebGL render, including it gyro sensor.

If your Oculus Go browser didn't give any respon on that, it meaning Oculus Go broswer not compatible with panolens.

Cheers,
sonic40

**Comment by donblaauw** [comment]
Well. If Aframe has it working, which has the same base on Three.js  and WebGL as Panolens, it should be possible..

**Comment by MahmoudAbdElMoneam** [comment]
We are using it, and it works, you need to make sure you are accessing your web page through HTTPS.
For the Sensors we used the following code (Not sure if we updated it elsewhere):

`function areDeviceSensorsAvailable() {
    //to request sensors permissions
    if (typeof (DeviceMotionEvent) !== "undefined" && typeof (DeviceMotionEvent.requestPermission) === "function") {
        // (optional) Do something before API request prompt.
        DeviceMotionEvent.requestPermission()
            .then(response => {
                // (optional) Do something after API prompt dismissed.
                if (response == "granted") {
                    window.addEventListener("devicemotion", (e) => {
                        // do something for 'e' here.
                    })
                    return true;
                }
            })
            .catch(console.error)

    } else {
        //alert("Couldn't access Device Sensors");
    }
    return false;
}`
