### ISSUE TITLE
Stereoscopic panoramas support

### ISSUE THREAD

**Issue by mbazaczek** [pchen66/panolens.js#15]
Hey, great piece of software!

Quick question: do you plan to add support for stereoscopic panoramas (VR mode?)

Best!
MBZ

**Comment by pchen66** [comment]
Yes, it will be part of the roadmap as well. :)

**Comment by pchen66** [comment]
It's added in [dev](https://github.com/pchen66/panolens.js/tree/dev) branch. Now it supports normal, cardboard, and stereoscopic modes. :) Please take a look at [Examples](http://pchen66.github.io/Panolens/#Example).
