### ISSUE TITLE
Disable mousewheel 

### ISSUE THREAD

**Issue by Maadtin** [pchen66/panolens.js#153]
Hello, Is there anyway to disable mousewheel zoom out / in to be able to scroll the page?

**Comment by claytonrothschild** [comment]
Use `viewer.OrbitControls.noZoom = true;`

**Comment by trainoasis** [comment]
@claytonrothschild this works, but is there an option to only disable zoom out, but allow zoom in to a certain degree? Thanks!

**Comment by Lorenzito** [comment]
@trainoasis you can specify the min and max Fov:
      viewer.OrbitControls.minFov= 55;
      viewer.OrbitControls.maxFov= 80;
