### ISSUE TITLE
Click/Hover events triggers for infospots outside the rendered screen

### ISSUE THREAD

**Issue by qria** [pchen66/panolens.js#155]
We had weird phenomenon of click event randomly triggering so I isolated it to following:

1. It happens for infospot outside of rendering

1. It stops happening after infospot has been loaded into screen at least once.

Here is the codepen to reproduce this issue: https://codepen.io/anon/pen/bjaXYm?editors=1111

Wait until the screen gets loaded and shake your mouse a bit, you'll see that hover event is triggered for infospot not in the viewing range.

Unfortunate for me I have not enough experience with threejs and canvas to debug this further.

Any ideas on why this might happen?

**Comment by qria** [comment]
I have also posted this on [threejs discourse](https://discourse.threejs.org/t/problematic-raycasting-of-offscreen-three-sprite-object/3644)

**Comment by qria** [comment]
To summarize the discourse post, I strongly suspect this is a threejs bug. Raycasting for sprite objects reference `modelViewMatrix` property, which only gets updated when the object is rendered. So when click/hover event happens, raycaster erronously report collisions with offscreen infospot objects that have incorrect `modelViewMatrix` value.

**Comment by qria** [comment]
The bug was confirmed to be a threejs bug. [Here](https://github.com/mrdoob/three.js/issues/14624) is the relevant issue.

**Comment by goodwin74** [comment]
I had an old three js from 06/29/2017.I decided to insert it, instead of three js 2019. The problem with not rendered hotspot is gone!
If someone needs the old three js, here is the link [https://yadi.sk/i/jZFgN9z719QA-A](url)
