### ISSUE TITLE
Need help to show loader on every pano LOAD

### ISSUE THREAD

**Issue by narkhedetushar** [pchen66/panolens.js#159]
I want to show something like below on every pano Load or any transition, I tried below method but not able to trigger for every pano load,

_panorama.addEventListener('progress');_

https://pannellum.org/documentation/examples/simple-example/

**Comment by webfalcon** [comment]
You need to add  event listener:

```
panorama.addEventListener('progress', function(e){
   // show the loader
});

panorama.addEventListener('load', function(e){
   // hide the loader
});
```

If you have multiple panorama you need to add the event listener to each panorama not the global viewer.
