### ISSUE TITLE
How a can get position(x,y,z) on click(tap) to panoram?

### ISSUE THREAD

**Issue by davids46** [pchen66/panolens.js#160]
Hello!
Thanks for awesome work! 

How a can get position(x,y,z) on click(tap) to panorama?

**Comment by pans0911** [comment]
do you get the soulution?Help

**Comment by pans0911** [comment]
> Hello!
> Thanks for awesome work!
> 
> How a can get position(x,y,z) on click(tap) to panoram?

do you get the soulution?Help

**Comment by davids46** [comment]
No
waiting...

**Comment by telebaslr** [comment]
Could you please reformulate your request? You want the coordinates under your mouse? Simply open the development console and press shift, thats it.

**Comment by davids46** [comment]
Yes, I would like to get the coordinates of the mouse that I get in the console (overlay), only on the event of a mouseclick on the panorama (without the CTRL)

**Comment by telebaslr** [comment]
This is not rocket science either. Just look at the panolens.js code:
```
	/**
	 * Output infospot attach position in developer console by holding down Ctrl button
	 */
	PANOLENS.Viewer.prototype.outputInfospotPosition = function () {

		var intersects, point, panoramaWorldPosition, outputPosition;

		intersects = this.raycaster.intersectObject( this.panorama, true );

		if ( intersects.length > 0 ) {

			point = intersects[0].point;
			panoramaWorldPosition = this.panorama.getWorldPosition();

			// Panorama is scaled -1 on X axis
			outputPosition = new THREE.Vector3(
				-(point.x - panoramaWorldPosition.x).toFixed(2),
				(point.y - panoramaWorldPosition.y).toFixed(2),
				(point.z - panoramaWorldPosition.z).toFixed(2)
			);

			switch ( this.options.output ) {

				case 'console':
					console.info( outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z );
					break;

				case 'overlay':
					this.outputDivElement.textContent = outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z;
					break;

				default:
					break;

			}

		}

	};
```
You need to add an event listener to the panorama and then implement the `console.info` function with all its parameters.

**Comment by davids46** [comment]
Thanks!

**Comment by siddharthso** [comment]
Hi,

Am trying to get the x,y,z, coordinates based on a mouse click and stored in a variable that is accessible through a variable to other pages where the Panorama is displayed. Having a challenge in implementing this. Is there any example, that you can post to solve this?
Thanks

**Comment by mcfry** [comment]
Add this to your panolens.js

```
PANOLENS.Viewer.prototype.getPosition = function () {
	var intersects, point, panoramaWorldPosition, outputPosition;
	intersects = this.raycaster.intersectObject( this.panorama, true );

	if ( intersects.length > 0 ) {
		point = intersects[0].point;
		panoramaWorldPosition = this.panorama.getWorldPosition();

		// Panorama is scaled -1 on X axis
		outputPosition = new THREE.Vector3(
			-(point.x - panoramaWorldPosition.x).toFixed(2),
			(point.y - panoramaWorldPosition.y).toFixed(2),
			(point.z - panoramaWorldPosition.z).toFixed(2)
		);
	}

	return outputPosition;
};
```

And then do something like...

```
let infospot = new PANOLENS.Infospot(600, IMGSOURCE);
let clickedPos = this.viewer.getPosition();
infospot.position.set(clickedPos.x, clickedPos.y, clickedPos.z);

this.panorama.add(infospot);
this.panorama.toggleInfospotVisibility(true);
```

**Comment by dev-ahmad** [comment]
@mcfry If I run your solution on mobile screen, ( intersects.length  ) is zero, I can't get the coordinates on mobile screen, any solution please?

**Comment by z6tanker** [comment]
> @mcfry @telebaslr If I run your solution on mobile screen, ( intersects.length ) is zero, I can't get the coordinates on mobile screen, or if you apply responsive mode on the browser.
> any solution please?

Any solutions?

**Comment by rudestewing** [comment]
> This is not rocket science either. Just look at the panolens.js code:
> 
> ```
> 	/**
> 	 * Output infospot attach position in developer console by holding down Ctrl button
> 	 */
> 	PANOLENS.Viewer.prototype.outputInfospotPosition = function () {
> 
> 		var intersects, point, panoramaWorldPosition, outputPosition;
> 
> 		intersects = this.raycaster.intersectObject( this.panorama, true );
> 
> 		if ( intersects.length > 0 ) {
> 
> 			point = intersects[0].point;
> 			panoramaWorldPosition = this.panorama.getWorldPosition();
> 
> 			// Panorama is scaled -1 on X axis
> 			outputPosition = new THREE.Vector3(
> 				-(point.x - panoramaWorldPosition.x).toFixed(2),
> 				(point.y - panoramaWorldPosition.y).toFixed(2),
> 				(point.z - panoramaWorldPosition.z).toFixed(2)
> 			);
> 
> 			switch ( this.options.output ) {
> 
> 				case 'console':
> 					console.info( outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z );
> 					break;
> 
> 				case 'overlay':
> 					this.outputDivElement.textContent = outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z;
> 					break;
> 
> 				default:
> 					break;
> 
> 			}
> 
> 		}
> 
> 	};
> ```
> 
> You need to add an event listener to the panorama and then implement the `console.info` function with all its parameters.

thank you , you saved my life

**Comment by mrvn-plby** [comment]
> > This is not rocket science either. Just look at the panolens.js code:
> > ```
> > 	/**
> > 	 * Output infospot attach position in developer console by holding down Ctrl button
> > 	 */
> > 	PANOLENS.Viewer.prototype.outputInfospotPosition = function () {
> > 
> > 		var intersects, point, panoramaWorldPosition, outputPosition;
> > 
> > 		intersects = this.raycaster.intersectObject( this.panorama, true );
> > 
> > 		if ( intersects.length > 0 ) {
> > 
> > 			point = intersects[0].point;
> > 			panoramaWorldPosition = this.panorama.getWorldPosition();
> > 
> > 			// Panorama is scaled -1 on X axis
> > 			outputPosition = new THREE.Vector3(
> > 				-(point.x - panoramaWorldPosition.x).toFixed(2),
> > 				(point.y - panoramaWorldPosition.y).toFixed(2),
> > 				(point.z - panoramaWorldPosition.z).toFixed(2)
> > 			);
> > 
> > 			switch ( this.options.output ) {
> > 
> > 				case 'console':
> > 					console.info( outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z );
> > 					break;
> > 
> > 				case 'overlay':
> > 					this.outputDivElement.textContent = outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z;
> > 					break;
> > 
> > 				default:
> > 					break;
> > 
> > 			}
> > 
> > 		}
> > 
> > 	};
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You need to add an event listener to the panorama and then implement the `console.info` function with all its parameters.
> 
> thank you , you saved my life



> This is not rocket science either. Just look at the panolens.js code:
> 
> ```
> 	/**
> 	 * Output infospot attach position in developer console by holding down Ctrl button
> 	 */
> 	PANOLENS.Viewer.prototype.outputInfospotPosition = function () {
> 
> 		var intersects, point, panoramaWorldPosition, outputPosition;
> 
> 		intersects = this.raycaster.intersectObject( this.panorama, true );
> 
> 		if ( intersects.length > 0 ) {
> 
> 			point = intersects[0].point;
> 			panoramaWorldPosition = this.panorama.getWorldPosition();
> 
> 			// Panorama is scaled -1 on X axis
> 			outputPosition = new THREE.Vector3(
> 				-(point.x - panoramaWorldPosition.x).toFixed(2),
> 				(point.y - panoramaWorldPosition.y).toFixed(2),
> 				(point.z - panoramaWorldPosition.z).toFixed(2)
> 			);
> 
> 			switch ( this.options.output ) {
> 
> 				case 'console':
> 					console.info( outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z );
> 					break;
> 
> 				case 'overlay':
> 					this.outputDivElement.textContent = outputPosition.x + ', ' + outputPosition.y + ', ' + outputPosition.z;
> 					break;
> 
> 				default:
> 					break;
> 
> 			}
> 
> 		}
> 
> 	};
> ```
> 
> You need to add an event listener to the panorama and then implement the `console.info` function with all its parameters.

How? I am newbie. Thank you

**Comment by lucychen0103** [comment]
for others looking for a solution, I think (but am not sure as I'm new to coding) that this works: 

```
function getPosition() { 
  const a = viewer.raycaster.intersectObject(viewer.panorama, true)[0].point;
  return a;
};
```

**Comment by mahshidmotie** [comment]
Hi There,

what is the replace for holding control and clicking on touch screens for getting x,y,z?
