### ISSUE TITLE
How to stop Infospots from rotating?

### ISSUE THREAD

**Issue by telebaslr** [pchen66/panolens.js#161]
Hi there,

I want to stop the infospots from rotating when I move up and down. Couldn't found anything related to it in the code. I would like to implement the Infospot just like a static tile.

And btw. PR #151 should really get implemented...

**Comment by IamITGeneralist** [comment]
> Hi there,
> 
> I want to stop the infospots from rotating when I move up and down. Couldn't found anything related to it in the code. I would like to implement the Infospot just like a static tile.
> 
> And btw. PR #151 should really get implemented...

Did you get any solution for this? I am also looking for similar solution.

**Comment by tinchoforever** [comment]
Waiting for this too.
