### ISSUE TITLE
Intermittent black screen when calling viewer.setPanorama()

### ISSUE THREAD

**Issue by nathanwoulfe** [pchen66/panolens.js#162]
I'm seeing an intermittent blackout when calling the viewer.setPanorama() method, page is an AngularJs app (if that matters).

I'm adding a menu element to the DOM then iterating through the menu links to bind the click handler:

```
scope.menu.forEach((m, i) => {
    const menuLink = document.getElementById(`menulink-${i}`);
    menuLink.addEventListener('click', onMenuClick.bind(this, i));
});
```
`onMenuClick` looks like this:

```
const onMenuClick = i => {
    panoService.setPano(i);
};
```

and calls into my AngularJs factory `panoService`, where `setPano()` looks like this:

```
setPano: i => {
    _viewer.setPanorama(_panos[i]);
},
```

in the service, `_panos` is a previously populated array of PANOLENS.ImagePanoramas. Essentially I'm using the service to store state, to make the whole app pluggable.

The issue appears after clicking through a few menu items (sometimes a couple, sometimes I can hit all items at least once before the error). I don't get anything logged, inspecting `_viewer` has the correct panorama set, but not displayed.

Is there anything obviously wrong with my approach which could be causing this?

**Comment by nathanwoulfe** [comment]
I think I've tracked this down to setting the center on the incoming panorama: 

```
const onEnterFadeStart = e => {
    _viewer.tweenControlCenter(new THREE.Vector3(// x,y,z are available on e.target), 0);
};
p.addEventListener('enter-fade-start', onEnterFadeStart);
```

I'm adding the desired center coordinates in other code, they exist in a property on the Panorama object (and always have values).

Removing the listener solves the problem, but I need to be able to set the starting center point for the incoming panorama...

**Comment by garymould** [comment]
Hi @nathanwoulfe ,

I am having the same issue, I think this is a Firefox problem.

It happens on the 'Initial Lookat' Codepen demo too: https://codepen.io/pchen66/pen/LLgxME

If I select back and forth between the panoramas in Firefox, it shows a black screen after roughly 8 clicks, but in Chrome it seems to work every time.

I wonder if it is linked to these ThreeJS warnings?:
"THREE.Object3D: .getWorldPosition() target is now required"
"THREE.Camera: .getWorldDirection() target is now required"
