### ISSUE TITLE
Orbit momentum and dampening

### ISSUE THREAD

**Issue by claytonrothschild** [pchen66/panolens.js#166]
Has anyone determined how to make the drag controls more responsive to mouse movement?

On Panolens, one must drag their mouse a large distance to get the scene to orbit a small distance. Additionally, if one drags quickly, the velocity is transferred to the scene orbit and the scene will spin too fast.

I would prefer no velocity and 1:1 drag to scene movement. As you can see in the first and second links below, there is too much velocity.

For example, use your mouse to move around the following.
contrast the demo tour:
https://pchen66.github.io/Panolens/examples/panorama_image.html
with my own implementation of panolens:
https://app.cloudpano.com/tours/t1LtFvj5DK
with google maps: 
https://goo.gl/maps/xaMcd9PDsDT2

I believe the fix is here... but would love to hear what other settings people have used to get the orbit more responsive. Thanks.

```
	// Momentum
  	this.momentumDampingFactor = 0.90;
  	this.momentumScalingFactor = -0.005;
  	this.momentumKeydownFactor = 20;
```

**Comment by goodwin74** [comment]
in panolens.min.js 
`N.rotateLeft(2*Math.PI*L.x/e.clientWidth*N.rotateSpeed)`
replace
`N.rotateLeft(2*Math.PI*2.8*L.x/e.clientWidth*N.rotateSpeed)`

now the camera is moving faster
