### ISSUE TITLE
Position images in certain angle

### ISSUE THREAD

**Issue by prajwalbati** [pchen66/panolens.js#167]
Can you please suggest me, how i can set the position for the 360 panoroma images? I want to show image in certain position when new image is displayed with linking.

Thank you

**Comment by mrintoul** [comment]
I'm not sure if the API currently allows for setting the angle of images, but you can set where to point at when the panorama loads. See the [example here](https://codepen.io/pchen66/pen/LLgxME)

**Comment by claytonrothschild** [comment]
The API example linked above is definitely the best way to set initial view on Panolens.

You can also set the camera position directly like so:
ie,
```
viewer.camera.position.set(position.x, position.y, position.z);
```

You can set zoom or other properties this way as well:

```
this.viewer.getCamera().fov = 90;
```

This is the prototypical ThreeJS camera, so the documentation applies: https://threejs.org/docs/#api/en/cameras/PerspectiveCamera

**Comment by rauwebieten** [comment]
Why is this closed? This still has issues.

I understand I can change the camera position at runtime, for example with event handlers.

Problem is this: (even visible in the codepen mentioned above)
When setting the new camera position on enter-fade-start. You see the camera movement on the leaving pano.
So you see the "leaving" pano jump to the position of the "entering" pano.

There is not a good moment in time to change the position of the camera: you either see the "leaving" or the "entering" pano make the jump.
