### ISSUE TITLE
WebGL ContextLost when load image many times

### ISSUE THREAD

**Issue by kde12327** [pchen66/panolens.js#169]
When I load image with ImagePanorama class, it makes WebGL ContextLost after many times loading with load().
```
<button type = "button" id = "change" >Change1</button>
<script type="text/javascript">
var panorama, viewer;
panorama = new PANOLENS.ImagePanorama(imageSource1 );

viewer = new PANOLENS.Viewer({output : 'console'});
viewer.add( panorama );
$("#change").text("Change1");

$("#change").click(function(){
  if($("#change").text() == "Change1"){
    panorama.load(imageSource2);
    $("#change").text("Change2");
  }else{
    panorama.load(imageSource1);
    $("#change").text("Change1");
  }
});
</script>
```

This is simple test code and on my computer when I click button 30 times it makes 'WebGL ContextLost'.

https://github.com/pchen66/panolens.js/issues/105
This issue looks similar, but (maybe) not resolved...(leaking test also makes error, too)

And the larger image size makes the earlier error.

I don't know reason, so tell me something to check or solution, plz.

**Comment by claytonrothschild** [comment]
Any update on this?

**Comment by pchen66** [comment]
I'm suspecting it's related to texture not being released properly. I've used your scenario and created a sandbox [Debug - WebGLContext Lost](https://codepen.io/pchen66/pen/YoXaMw), can you tell me if you can still reproduce it? and your OS, browser, version as well.

If you did successfully reproduce it, uncomment this line to see if it makes a difference
```
panorama.material.map.dispose();
```

**Comment by claytonrothschild** [comment]
I can confirm that this line seems to make an enormous difference:

`panorama.material.map.dispose();`

When switching scenes using my own methods, I would `dispose()` the panorama and then remove it. However memory would keep climbing with each scene switch. On mobile it would crash after 20 scene switches.

This keeps memory super low!!! If anyone can advise how to profile it, let me know. I tried profiling it in Chrome dev tools but cant seem to work it right. But when I watch my Chrome process for memory consumption I see a big difference.

Thank you!

**Comment by felipenegrelli** [comment]
I'm having this same issue. I'm using the plugin to create a StreetView style Pano navigator, using Openlayers. The user can select from thousands of images, so I have to create the panorama after user selects a point fom the map, so I can't preload all panoramas.

I tried creating a new Parorama using the image url each time, but by the fifth Panorama added and showed I get an "WebGLContext Lost" as ubove.

I tried removing the old panorama before adding the new one or after inserting the new one, but the error is still there.

I tried disposing the old panorama before creating a new one using "panorama.dispose()", but a different error showed up.

The only solution for me is to to use only one Panorama changing the image using the "updateTexture" function. It works, but a black screen is shown as this method problaby doesn't have a fading animation like "setPanorama" does.

I tried implementing the animation on "updateTextute", with no success.

I looked at the codepen created by @pchen66, but could not find the "panorama.material.map.dispose();" line. I tried using "material.map.dispose" on my panorama, but didn't make a difference for me.

Pano images are about ~4mb in size and resolution of 11k x 5.5k. Testing in Chrome 75 and Windows 10.

Any ideas on removing the black screen when using "updateTexture" or create multiple panoramas without crashing?

Thank you for this great tool, by the way!

**Comment by claytonrothschild** [comment]
Dealing with ContextLoss problems with v0.11.

Looking through the new upgrade Panolens v0.11 codebase, I see the `.dispose()` method of ImagePanorama looks different than `.dispose` method of Infospot when getting rid of the map. 

ImagePanorama:
```
	    /**
	     * Dispose
	     * @memberOf ImagePanorama
	     * @instance
	     */
	    dispose: function () {

	        const { material: { map } } = this;

	        // Release cached image
	        THREE.Cache.remove( this.src );

	        if ( map ) { map.dispose(); }

	        Panorama.prototype.dispose.call( this );

	    }
```

Infospot:
```
	    /**
	     * Dispose
	     * @memberOf Infospot
	     * @instance
	     */
	    dispose: function () {

	        const { geometry, material } = this;
	        const { map } = material;

	        this.removeHoverElement();

	        if ( this.parent ) {

	            this.parent.remove( this );

	        }

	        if ( map ) { map.dispose(); material.map = null; }
	        if ( geometry ) { geometry.dispose(); this.geometry = null; }
	        if ( material ) { material.dispose(); this.material = null; }

	    }
```


This looks fishy to me: `const { material: { map } } = this;`

Anyway, in the past (before v0.11 - I think r9) I went nuclear and used this to fix context loss problems:
```
    this.viewer.panorama.dispose();
    this.panorama.dispose();
    this.viewer.renderer.dispose();
    this.viewer.renderer.forceContextLoss();
    this.viewer.panorama.material.map.dispose()
```
I got rid of this when v0.11 came out because thought it was no longer needed. Maybe I am wrong. All are welcome to try. Please write back on effectiveness. I think that `.forceContextLoss()` was the method that fixes all.
