### ISSUE TITLE
panoramaImage defect when rotated

### ISSUE THREAD

**Issue by Zhdanown** [pchen66/panolens.js#170]
I've got a strange defect when switching between panoramas:

![panorama](https://user-images.githubusercontent.com/29001510/53228142-5f631e80-3691-11e9-99f6-24de5e756177.jpg)

I believe the reason is this line of code:
`panorama.rotation.y = adjustment_angle * Math.PI / 180`

I need to be able to set initial rotation of panorama when it loads. I know i can use `OrbitControls.rotateLeft()`  for this, but i have a 'change' listener on OrbitControls, which syncs field of view on a 2d map with that panorama, so camera manipulation is off limits.

I've tried to hide that defect by showing loader screen with these events:
`enter-animation-start` to turn on the loader screen and `enter-animation-complete`, `leave-complete`, `enter-fade-complete` to turn off, but the defect still appears.

The question is can i get rid off this defect or hide it somehow?

**Comment by Dorian76453** [comment]
I have same problem, but i don't have this code 
`panorama.rotation.y = adjustment_angle * Math.PI / 180`

**Comment by biorev3pp** [comment]
I also have the same problem

**Comment by Luze26** [comment]
Same problem here, someone have a solution?
