### ISSUE TITLE
the title or content on a hotspot icon to alway display

### ISSUE THREAD

**Issue by yoyomule** [pchen66/panolens.js#171]
I want the title or content on a hotspot icon to always be displayed, what should I do? At present, it is only possible to display the content after moving the mouse there.Thanks.

**Comment by claytonrothschild** [comment]
Call `lockHoverElement()` on your infospot.

eg
```
let infospot = new PANOLENS.infospot();
infospot.addHoverText('Text);
infospot.lockHoverElement();
```

https://pchen66.github.io/Panolens/docs/PANOLENS.Infospot.html#lockHoverElement__anchor

**Comment by yoyomule** [comment]
Thank you for your reply. Sorry, I didn't express my question very well. I mean, when the panorama is loaded, the title text is automatically displayed, not just after clicking it. In addition, we have another problem. When the title is loaded, if I want to click the button under the title to load the "hoverelement" element (such as a picture), it seems impossible.

**Comment by claytonrothschild** [comment]
If you lock hover element immediately after adding it to panorama then you never have to click the infospot. It will show it by default.

And yeah, you can only have one hover element of any kind for a given hotspot. So element or text, but not both. However, this would be a pretty easy change to make to the library to allow both. In addHoverElement it wipes out all children that may already exist. Simply remove the wipe out and instead appendChild.

Sent from my iPhone

On Apr 8, 2019, at 11:17 PM, yoyomule <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for your reply. Sorry, I didn't express my question very well. I mean, when the panorama is loaded, the title text is automatically displayed, not just after clicking it. In addition, we have another problem. When the title is loaded, if I want to click the button under the title to load the "hoverelement" element (such as a picture), it seems impossible.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://protect-us.mimecast.com/s/Yw0ZCQWN2VhkW858IxX4u0>, or mute the thread<https://protect-us.mimecast.com/s/_7nCCR6M0WSvLJAJfNZetj>.



**This message originated from outside Pariveda Solutions**

**Comment by claytonrothschild** [comment]
Update: Looks like lockHoverElement does NOT always display it, only keeps displaying after initial hover.

So I think the solution here is as follows: you can display the hover element by default by editing Infospot.js:416 to not set `display:none` after cloning the Element. instead just set it to `display:block`.

https://github.com/pchen66/panolens.js/blob/master/src/infospot/Infospot.js#L416

**Comment by yoyomule** [comment]
Thank you. It seems that there is still a problem with this. The position of the text is not related to the icon point. The initial position will be in the upper left corner of the screen.

**Comment by claytonrothschild** [comment]
Try adding the other styles that are applied onHoverEnter:

https://github.com/pchen66/panolens.js/blob/master/src/infospot/Infospot.js#L214

**Comment by yoyomule** [comment]
Thanks, this doesn't seem easy. When the text loads, it will run to the upper left corner, which should be the 0,0 coordinate position. I thought of a way to write the text in the canvas of the icon, maybe it works, I am trying.

**Comment by xofa** [comment]
i try to always display content too,but failed..any better ideas?

**Comment by RamenKebab** [comment]
> Update: Looks like lockHoverElement does NOT always display it, only keeps displaying after initial hover.
> 
> So I think the solution here is as follows: you can display the hover element by default by editing Infospot.js:416 to not set `display:none` after cloning the Element. instead just set it to `display:block`.
> 
> https://github.com/pchen66/panolens.js/blob/master/src/infospot/Infospot.js#L416

Dear @claytonrothschild, this solution seems perfect for my case. However, I am using panolens.min.js (master). I never called infospot.js in my html. However, to have custom infospots, it seems necessary to work with it, but how can I do that ? I feel like it would interfere with panolens.min. What js scripts should I call in my html ? (beginner in coding)

Thank you very much for your help.

**Comment by RamenKebab** [comment]
@claytonrothschild I found the same line in panolens.min and changed the display to block. However, it did nothing...

addHoverText:function(a,b){b=void 0===b?40:b;this.element||(this.element=document.createElement("div"),
**this.element.style.display="block",**
this.element.style.color="#fff",
this.element.style.top=0,this.element.style.maxWidth="50%",
this.element.style.maxHeight="50%",
this.element.style.textShadow="0 0 0px #000000",
this.element.style.fontFamily='"Arial", Helvetica, sans-serif',

**Comment by claytonrothschild** [comment]
Dont work directly with .min, rather download the repo, make the change in infospot.js, then run `npm run build:dev` or whatever relevant script is in package.json. Research "Run NPM project" for more information, as this is a general development competency

**Comment by joscelyn** [comment]
Just set `this.element.style.display="block"` will not work, you have to copy the [onHoverStart](https://github.com/pchen66/panolens.js/blob/562ff9d732d7872fa54eb7fb011ba0788f8bc104/src/infospot/Infospot.js#L210) function as :
`                    
                const infospot = new PANOLENS.Infospot(300, PANOLENS.DataImage.Arrow, false)
               infospot.position.set(-1870, 89, -4626)
                infospot.addHoverText('The Where Is Bar')
                infospot.lockHoverElement()
                panorama.add(infospot)
                    
                    const { scaleDownAnimation, scaleUpAnimation, element } = infospot;
                    infospot.isHovering = true;
                    
                    if ( infospot.animated ) {
                        scaleDownAnimation.stop();
                        scaleUpAnimation.start();
                    }
                    
                    const { left, right, style } = element;
                    
                    style.display = 'block';
                    if ( left ) { left.style.display = 'none'; }
                    if ( right ) { right.style.display = 'none'; }
                    
                    element._width = element.clientWidth;
                    element._height = element.clientHeight;`
