### ISSUE TITLE
drawing lines in the panorama 

### ISSUE THREAD

**Issue by yoyomule** [pchen66/panolens.js#175]
I hope to get some suggestions for drawing lines in the panorama to mark the area and position, just like the one below.Thanks
![image](https://user-images.githubusercontent.com/10000818/56190535-f9759080-605c-11e9-9bfc-c76e4fe451ec.png)

**Comment by LadonAl** [comment]
were you able to find anything?

**Comment by LadonAl** [comment]
IDK if there is a direct way to achieve this using PANOLENS methods. However you could always play with THREE.js. I was able to achieve something similar using this:

```
var geometry = new window.THREE.Geometry();
geometry.vertices.push(point1); //  point1 is a Vector3 
geometry.vertices.push(point2);
// add more points 

var material = new window.THREE.LineBasicMaterial({ color: 0x0000FF });

var line = new window.THREE.Line(geometry, material, window.THREE.LinePieces);

viewer.panorama.add(line);
```

Cheers. Please lmk if you find something better.

**Comment by 3DGISKing** [comment]
Hi, LadonAl, Definitely your code works for me.
I did not find something better to draw a line. I think your idea is enough for this issue.
