### ISSUE TITLE
Is There a way to find out position and add hotpots on mouseclick

### ISSUE THREAD

**Issue by upardhi** [pchen66/panolens.js#177]
Hi,

Thanks in advance.

I am trying to add hotspot when user click right clicks on panorama image. I am not getting the exact point where I want to set the object dynamically. Can you please help me to achieve this?

One more question: How can I set responsive behavior?

I have searched in your document and net but unable to find out the details.

**Comment by z6tanker** [comment]
@upardhi Did you end up figuring this out?
