### ISSUE TITLE
Getting a black screen when trying to focus on an infospot

### ISSUE THREAD

**Issue by ccamero8** [pchen66/panolens.js#179]
I haven't been able to get the Infospot.Focus method to work correctly. When I add a new infospot to my panorama, the infospot shows. However, when I click on it, the entire viewer turns black.

`                        
                    
                   else {

                            var newInfospot = {
                                panoramaId: vm.currentPanorama.panoramaId,
                                text: result.text,
                                point: {x: position.x, y: position.y, z: position.z},
                                type: "Infospot"
                            };

                            infospotService.createInfospot(newInfospot); // async call, not important

                            var infospot = new PANOLENS.Infospot(350, PANOLENS.DataImage.Info);

                            infospot.addEventListener('click', onFocus);

                            infospot.position.set(position.x, position.y, position.z);

                            infospot.addHoverText(result.text, 30);

                        }

                        viewer.panorama.add(infospot);

                        infospot.show();`

**Comment by asfshop** [comment]
hi, I have this problem too, can anyone please help please

**Comment by loftykhanna** [comment]
I faced the same issue, just make sure  positions in   infospot.position.set(position.x, position.y, position.z) are not string,

**Comment by adam-sal** [comment]
any update in this case?

**Comment by goonarr** [comment]
> 
> 
> I faced the same issue, just make sure positions in infospot.position.set(position.x, position.y, position.z) are not string,

Just tested, this is the solution. So in code above edit line so looks like this:
`point: {x: parseInt(position.x), y: parseInt(position.y), z: parseInt(position.z)},`
