### ISSUE TITLE
How to detect when a video finishes?

### ISSUE THREAD

**Issue by ruizrube** [pchen66/panolens.js#184]
Hi.

I can't find in the documentation any event which is triggered when a videopanorama finishes. Is it possible?

Thanks.

**Comment by chiragpurohit71085** [comment]
Hi @ruizrube 

I am not sure this is proper way or not, but I have achieved using following

`var panorama_main_video = new PANOLENS.VideoPanorama( 'asset/textures/video/pano.mp4', { autoplay: true, muted: true,loop:false });
panorama_main_video.setLinkingImage( 'asset/textures/danger.png' );

var videoElementMain = panorama_main_video.getVideoElement();
videoElementMain.ontimeupdate = function() {

	console.log("videoElement duration - ",videoElementMain.duration);
	console.log("videoElement currentTime - ",videoElementMain.currentTime);

};

videoElementMain.onended = function() {

	 alert("The audio has ended");

};`
