### ISSUE TITLE
how to set horizontalview true on sensor Control

### ISSUE THREAD

**Issue by ktrendy** [pchen66/panolens.js#185]
I have set horizontalview  true on viewer like this:
viewer = new PANOLENS.Viewer( { container: container, horizontalView: true   } );

So it is working on page load (touch control) but when i change the control to sensor, It is not working. Please check it and let me know, how can i use horizontalview  true with viewer.enableControl( PANOLENS.CONTROLS.DEVICEORIENTATION );

For example, you can test it on: https://codepen.io/kuldeepjain11/pen/zVVvyy

**Comment by claytonrothschild** [comment]
Check out line 
https://github.com/pchen66/panolens.js/blob/master/src/viewer/Viewer.js#L198

```
 // Lock horizontal view
    if ( this.options.horizontalView ) {
        this.OrbitControls.minPolarAngle = Math.PI / 2;
        this.OrbitControls.maxPolarAngle = Math.PI / 2;
    }
```

You could try adding something like the following:

```
        this.DeviceOrientationControls.minPolarAngle = Math.PI / 2;
        this.DeviceOrientationControls.maxPolarAngle = Math.PI / 2;
```

I am unsure the DeviceOrientationControls API and if those properties are even available. But this is what I would try first.
