### ISSUE TITLE
How to convert camera position to THREE.Vector3

### ISSUE THREAD

**Issue by claytonrothschild** [pchen66/panolens.js#187]
Hi all,

I have historically used camera.position and setCamera to set initial views. I have the camera.position saved, and at scene load I set the camera to that saved camera.position.

`
// on scene load
this.viewer.camera.position.set(0, 6.123233995736766e-17, 1);`

I need to convert these to Vector3 so that I can use the built-in TweenControlCenter to set an initialLookAt. 

`
// on scene load
viewer.tweenControlCenter( new THREE.Vector3(1278.27, 732.65, 4769.19), 0 );`

Does anyone know how to convert all my saved `camera.position` to new `Vector3`?

I have scoured THREE.js documentation. I feel like I am missing something obvious. Any help is greatly appreciated. Thank you.

**Comment by claytonrothschild** [comment]
Came up with this. No idea why it works (why not add containerHeight to y camera position like we do for x?). Would love some insight. Thank you.
```
this.viewer.tweenControlCenter( new THREE.Vector3((position.x * (container.width/2)) + (container.width/2), (position.y.toFixed(2) * (container.height /2)), position.z), 1000 )
```

**Comment by claytonrothschild** [comment]
OK - the above would only work for the first scene change.

I ended up using camera.position for scene changes by creating my own TWEEN.

```
var tween = new TWEEN.Tween(this.viewer.camera.position)
      .to(myNewPosition,600)
      .easing(TWEEN.Easing.Exponential.Out)
      .onUpdate(() => {
        this.viewer.camera.lookAt(new THREE.Vector3(0,0,0));
      })
      .onComplete(() => {
        this.viewer.camera.lookAt(new THREE.Vector3(0,0,0));
      })
      .start();
```

I am satisfied with this solution.

Thanks,
Clayton

**Comment by hungvo2010** [comment]
Hi @claytonrothschild I want to drag the panorama smoothly during the tween, but your solution cannot let me do that. How can I fix this problem? Thanks
