### ISSUE TITLE
Is able to add babel? 

### ISSUE THREAD

**Issue by softenwareness** [pchen66/panolens.js#188]
##### Description

Describe the bug or issues with as much detail as possible. It'd be nice to have a code snippet or screenshots to better illustrate the problems.

Please also include a live example if possible. You can start from these templates:

* [codepen](https://codepen.io/pchen66/pen/YNXEQW) (dev branch)

##### Panolens version

- [ ] Master
- [ ] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by prosenba** [comment]
I completely uninstalled office
Rebooted
Used the link in the message for setup
The product asked for key and the site asked for my office  msn login
After installation
I started word and selected activate over internet
I get a message this license key has been activated too many times

That’s about it

Phillip
Sent from iPhone

On Aug 1, 2019, at 10:48 PM, softenwareness <notifications@github.com<mailto:notifications@github.com>> wrote:

Description

Describe the bug or issues with as much detail as possible. It'd be nice to have a code snippet or screenshots to better illustrate the problems.

Please also include a live example if possible. You can start from these templates:

  *   codepen<https://codepen.io/pchen66/pen/YNXEQW> (dev branch)

Panolens version

  *    Master
  *    Dev

Browser

  *    All of them
  *    Chrome
  *    Firefox
  *    Internet Explorer

OS

  *    All of them
  *    Windows
  *    macOS
  *    Linux
  *    Android
  *    iOS

Hardware Requirements (graphics card, VR Device, ...)

**Comment by prosenba** [comment]
This is a new dell desktop with windows 10 home

Phillip
Sent from iPhone

On Aug 1, 2019, at 10:48 PM, softenwareness <notifications@github.com<mailto:notifications@github.com>> wrote:

Description

Describe the bug or issues with as much detail as possible. It'd be nice to have a code snippet or screenshots to better illustrate the problems.

Please also include a live example if possible. You can start from these templates:

  *   codepen<https://codepen.io/pchen66/pen/YNXEQW> (dev branch)

Panolens version

  *    Master
  *    Dev

Browser

  *    All of them
  *    Chrome
  *    Firefox
  *    Internet Explorer

OS

  *    All of them
  *    Windows
  *    macOS
  *    Linux
  *    Android
  *    iOS

Hardware Requirements (graphics card, VR Device, ...)

**Comment by prosenba** [comment]
Thanks for the help phone registration worked

Phillip
Sent from iPhone

On Aug 1, 2019, at 10:48 PM, softenwareness <notifications@github.com<mailto:notifications@github.com>> wrote:

Description

Describe the bug or issues with as much detail as possible. It'd be nice to have a code snippet or screenshots to better illustrate the problems.

Please also include a live example if possible. You can start from these templates:

  *   codepen<https://codepen.io/pchen66/pen/YNXEQW> (dev branch)

Panolens version

  *    Master
  *    Dev

Browser

  *    All of them
  *    Chrome
  *    Firefox
  *    Internet Explorer

OS

  *    All of them
  *    Windows
  *    macOS
  *    Linux
  *    Android
  *    iOS

Hardware Requirements (graphics card, VR Device, ...)
