### ISSUE TITLE
cannot set  PANOLENS.CONTROLS.DEVICEORIENTATION if control bar is false

### ISSUE THREAD

**Issue by bharath-exads** [pchen66/panolens.js#190]
An exception
panolens.min.js:172 Uncaught TypeError: Cannot read property 'mainMenu' of null

is thrown when **vrViewer.enableEffect( PANOLENS.MODES.NORMAL );** 
if the **new PANOLENS.Viewer( { container: vrContainer, controlBar: false } );**

**Comment by claytonrothschild** [comment]
this is legit. One workaround without updating the code is to simply pass in `controlButtons: []` along with `controlBar:false`. With that said, someone (me?) should probably make a quick null check -> return early and open a PR.

**Comment by bharath-exads** [comment]
It worked.
Thanks for the help :)
:+1:
