### ISSUE TITLE
How to remove white dot on the screen in Cardboard Mode

### ISSUE THREAD

**Issue by bharath-exads** [pchen66/panolens.js#191]
Hi,

I am trying to implement VR cardboard player feature, But I can see a white dot appearing on the center of the screen during cardboard mode.

The white dot appearing despite making **controls: false**
Like to know if there is a way to hide it

Please click on cardboard icon 
https://fluidplayer-exads.firebaseapp.com/html/vr.html

**Comment by bharath-exads** [comment]
Screen Shot for the issue 
https://ibb.co/k3NqrZb

**Comment by claytonrothschild** [comment]
Instantiate viewer with `enableReticle: false`.

Or, later on call `disableReticleControl()` on viewer. https://pchen66.github.io/panolens.js/Viewer.html#disableReticleControl

**Comment by bharath-exads** [comment]
Thanks a Lot
It worked
