### ISSUE TITLE
rotateLeft with DEVICEORIENTATION active not work

### ISSUE THREAD

**Issue by babeone** [pchen66/panolens.js#193]
##### Description
if i'll set an initial view with this code: 

```javascript
viewer.getControl().rotateLeft( "mydegree" * Math.PI / 180);
viewer.getControl().update();
```

and after i'll enable the DeviceOrientation with: 

```javascript
viewer.enableControl(1);
```

i lose the rotateLeft command with my custom degree, and it set a default degree view.

This is the full code of what i'm trying to do:

```javascript
  var container = document.querySelector('#container');

  var viewer = new PANOLENS.Viewer({ 
    container: container, controlBar: false, cameraFov: 120 
   });

  const panorama = new PANOLENS.ImagePanorama('test.jpg');

  viewer.add(panorama);

  panorama.addEventListener('load', function () {
     if (viewer.getControl().getAzimuthalAngle() == 0) {
       viewer.getControl().rotateLeft( "mydegree" * Math.PI / 180);
       viewer.getControl().update();
       viewer.enableControl(1);
     }
  });
```

Thanks for the support

**Comment by claytonrothschild** [comment]
I suggest not setting initial view of the viewer in this way. You can use initialLookAt API to set the initial view.

In any case, device orientation indeed ignores initial views. Ray explored a solution here this summer and got pretty darn close. There is code in the dev branch that begins to allow device orientation controls to handle initial views. But we never landed on a final solution. Hopefully soon.
