### ISSUE TITLE
WebVR support

### ISSUE THREAD

**Issue by labmorales** [pchen66/panolens.js#196]
##### Description

How can i make my app WebVR compatible for usage with GearVR? The app works really well with panolens in chrome browser on mobile, all sensors and 360º pictures function very well. 

But in GearVR the sensors work on Samsung Internet Browser but not on Oculus Browser. And there's no option for full screen in WebVR. Is there a version o panolens with support for WebVR (https://webvr.info/)?

##### Panolens version

- [X] 0.9
- [ ] Master
- [ ] Dev

##### Browser

- [ ] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [X] Oculus Browser (GearVR)
- [X] Samsung Internet VR (GearVR)

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

GearVR and Samsung S9 were used for testing.

**Comment by claytonrothschild** [comment]
Did you get this working? I have been exploring it - should be straightforward but I cant test it to verify.

**Comment by labmorales** [comment]
Nope. Only option that i see is starting over with another tech that supports WebVR.

**Comment by claytonrothschild** [comment]
It seems compelling and very possible just to integrate something like this, since Panolens.js uses Three.JS for all rendering: https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content
