### ISSUE TITLE
walk through effect with panolens?

### ISSUE THREAD

**Issue by chendabo** [pchen66/panolens.js#202]
##### Description

when I use pano link, I can have a smooth transition from pano to pano.
is it possible to keep the orientation of the camera while making that transition?

right now, if you load the new pano, the camera will be reset to the default direction, resulting in the wrong orientation, which confuses people.

Is this possible with current panolens?if not, what would be the best way of achieving that?

Thanks!

**Comment by claytonrothschild** [comment]
I had good success reducing the duration of the fadeout. I put it at 200. Its still smooth but fast enough that the camera doesnt change before the pano is exited.

```
	    /**
	     * This will be called when leaving a panorama
	     * @memberOf Panorama
	     * @instance
	     * @fires Panorama#leave
	     */
	    onLeave: function () {

	        const duration = this.animationDuration;

	        this.enterTransition.stop();
	        this.leaveTransition
	            .to( {}, duration )
	            .onStart( function () {

	                /**
	                 * Leave panorama and animation starting event
	                 * @event Panorama#leave-start
	                 * @type {object} 
	                 */
	                this.dispatchEvent( { type: 'leave-start' } );

	                this.fadeOut( 200 );
	                this.toggleInfospotVisibility( false );

	            }.bind( this ) )
	            .start();
```
