### ISSUE TITLE
Custom Div disappears in full-screen mode.

### ISSUE THREAD

**Issue by kingbaggot** [pchen66/panolens.js#206]
I have a pop-up Div that appears when an infospot is clicked and when I go into fullscreen mode it disappears. 
Example is here.
https://magneticboots.com/h6/bentleypriory/360/

I *think* this is because full-screen only affects the panolens container - so what is the best way to associate my pop-up divs with this container ? 

Panolens version - 0.11.0
Three.js version 105
Browser chrome 77.x

**Comment by kaelaRoy** [comment]
Panolens already has something for this in the [viewer options](https://pchen66.github.io/panolens.js/Viewer.html). put all your content inside a wrapper div, and then set the container for the viewer you create to be that div. 
HTML:
```
<div id="wrapper">
    <!-- all your pop-up divs here-->
</div>
```
JS:
```viewer = new PANOLENS.Viewer({ container: document.getElementById('wrapper'), ... });```

this will create the canvas inside that div, and should reference the container div when fullscreen is used. you will need to set some styles to ensure the wrapper is filling the browser view, but this should be a start.

**Comment by kingbaggot** [comment]
that's great ! totally solves it for me. Thank you very much.

**Comment by silqwer** [comment]
Good~!
