### ISSUE TITLE
iPhone Safari iOS 13+ - no gyro motion device orientation

### ISSUE THREAD

**Issue by bulesz** [pchen66/panolens.js#207]
Hello,

After upgrading the iPhone iOS to version 13, I have lost the ability to use the device orientation gyro) control.

How to resolve this?

Is this fix can help?

https://dev.to/li/how-to-requestpermission-for-devicemotion-and-deviceorientation-events-in-ios-13-46g2

and / or

https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140

Many thanks,
Bulcsu

**Comment by wavilikhin** [comment]
Hey,

I tried first solution and it actually worked for me.

Just created a button with event listener:

` btn.addEventListener("click", function() {
        DeviceMotionEvent.requestPermission();
      });`

After clicking on it you will get a modal window asking for access

** NOTE: this will work only with https **
