### ISSUE TITLE
Radius property is in documentation, but not supported in library

### ISSUE THREAD

**Issue by alexxlagutin** [pchen66/panolens.js#208]
Hi there!
First of all thank you for a great library.

But i`m confused a bit and hope for your help

I use npm package with v  0.11.0

And I see two different documentations 
DOC_1: https://pchen66.github.io/panolens.js/
DOC_2: https://pchen66.github.io/Panolens/docs/index.html

In DOC_1 I see next notation: 
new ImagePanorama(image) 

Same time in DOC_2 I see for v.0.11.0 it is
new ImagePanorama(image [, radius]) 

Calling PANOLENS.ImagePanorama in console returns 
function ImagePanorama ( image, _geometry, _material )

Same situation is with VideoPanorama

Where am I wrong? Or it might be some trouble with version?

**Comment by AnubisAlves** [comment]
any update on this? I have the same issue
