### ISSUE TITLE
iPhone Safari | Chrome | Firefox iOS 13 autoplay is not working

### ISSUE THREAD

**Issue by Virtualmerse** [pchen66/panolens.js#211]
##### Description

Since I updated my iPhone to iOS 13, videos are not starting automatically. 

Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS
- [ ] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [X] iOS

I also checked on my iPad but here, videos are working properly. 

Thanks

Eduardo

**Comment by donblaauw** [comment]
I think it’s a Apple privacy decision where user interaction is obligatory. My application is using a start button for that now.

**Comment by mediamerse** [comment]
Hello Donblaauw, thanks for sharing but, do you mean a button different that the one at the left-bottom corner?
