### ISSUE TITLE
When "setVideoCurrentTime" runs, I want "tweenControlCenter" to run at the same time.

### ISSUE THREAD

**Issue by ddilddil** [pchen66/panolens.js#216]
When "setVideoCurrentTime" runs, I want "tweenControlCenter" to run at the same time.

In the code below, After "tweenControlCenter" executes, "setVideoCurrentTime" executes.

So, after clicking, the tweened previous screen is shown for a while and then it moves to the time I specified.

I want to look at the coordinates(ex. new THREE.Vector3(4849.18 , 173.39 , -1168.38) ) at a specified time(ex. percentage: 0.15).

How to fix ?

```
var self = this;
this.v_poi.addEventListener( 'click', function(){		
				self.video1.playVideo();
				self.video1.setVideoCurrentTime({ percentage: 0.15 });
				self.viewer.tweenControlCenter( new THREE.Vector3(4849.18 , 173.39 , -1168.38), 0);	
			});
```

**Comment by Marty-f13** [comment]
Can you do the second part as a callback of the setVideoCurrentTime function - that way you can make sure they fire together or even add a small delay

**Comment by flyandi** [comment]
yeah decouple with `setTimeout` is the easiest here.
