### ISSUE TITLE
Render a Partial Panorama

### ISSUE THREAD

**Issue by claytonrothschild** [pchen66/panolens.js#229]
Anyone have an idea of how to render a partial panorama with this library? I'm happy to modify the code a bit, just dont know the general direction to go here. 

For example, I want to use an iPhone panorama as an image.

I think I should project onto a sphere with vertical offset. If anyone is able to start a discussion with me on this, I would appreciate it a lot. Thank you.

**Comment by dustinkerstein** [comment]
What does the source image look like? You'd most likely need to re-project it in equirectangular with something like PTGui or Hugin.

**Comment by claytonrothschild** [comment]
I was able to render it by creating a new class called `PartialImagePanorama` in panolens. In it, the constructor instantiates a `SphereBufferGeometry` that only renders a partial (180 degree) sphere:
`geometry = new THREE.SphereBufferGeometry( 500, 60, 40, 0, Math.PI, 0, Math.PI );`

The general explanation can be found [here](https://stackoverflow.com/a/36878477). Best wishes!

**Comment by dustinkerstein** [comment]
Haha, that SO post was posted by me :) Glad to hear you got it working.

**Comment by dustinkerstein** [comment]
And that example can now be seen here - https://my.panomoments.com/u/MomentCaptureStudio/m/janes-carousel
