### ISSUE TITLE
Progress Bar in Video Panorama

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#24]
Hi,
I had tried with Adding Progress Bar in Video Panorama,but it seems like progress bar working only in Image panorama not in  video panorama.

Any hint?

**Comment by pchen66** [comment]
Yes, currently video panorama is not supported yet. It will come later.

**Comment by pchen66** [comment]
By default video element doesn't provide transparent progress, but once it triggers `loadeddata` event panolens would give you progress update saying the first frame of the media has finished loading.
Closed #82
