### ISSUE TITLE
Reticle uses infospot icon in Safari, when infospots exist in a scene

### ISSUE THREAD

**Issue by andymcpherson** [pchen66/panolens.js#25]
Steps to reproduce: 
Open the [infospot_focus](http://pchen66.github.io/Panolens/examples/panorama_infospot_focus.html) example in Safari and select the VR icon.
Reticle displays as an infospot icon.

Reticle appears normally if there are no infospots in the scene.

Tested under: Safari 9.1.1 (OSX 10.10.5), Safari 9.0.1 (iOS 9.0.1)

**Comment by pchen66** [comment]
After a few days of investigation, I realized safari has issue parsing data uri images in svg+xml format. So changing to png based approach fixed the issue. The example is using [dev](https://github.com/pchen66/panolens.js/tree/dev) branch.
