### ISSUE TITLE
Click on infospot to open a new web page does not work

### ISSUE THREAD

**Issue by htranboston** [pchen66/panolens.js#259]
I thought it would be simple. I want to open a webpage after clicking on an infospot. I have the following code but it does not work. Is there another way?

`infospot.addHoverText( "Soccer Bet Buddy" );
infospot.addEventListener( 'click', function(){
window.open("https://soccerbetbuddy.com");
} );`

Thanks

**Comment by flyandi** [comment]
are u sure your infospot is properly initialized? any errors in the console?
