### ISSUE TITLE
Add autoplay to VideoPanorama constructor

### ISSUE THREAD

**Issue by baseline-s** [pchen66/panolens.js#26]
Hi there,

Fantastic library.
Would it be possible to add autoplay as an option to VideoPanorama(src, options, radius) ? Is there a reason it's not built in, other than bandwidth consumption ?

**Comment by Japegrape** [comment]
In my very brief experimentation, videos do auto-play on Destop. Getting videos to play on Mobile is an entirely different beast, as it needs to be tied to a user action directly, or else the browsers ignore it.

**Comment by baseline-s** [comment]
The videos only autoplay on desktop if I modify your library to set the autoplay parameter. I am aware of the issues on a mobile and have not found a way to prevent the user action, but the control widget satisfies this requirement for me.

I added autoplay to the options parameter in your VideoPanorama constructor as can be seen below to ensure that the videos autoplay on a browser, but would like this added to your original code if possible.

PANOLENS.VideoPanorama.prototype.load = function ( src, options ) {
......
this.videoElement.muted = options.muted || false;
this.videoElement.loop = ( options.loop !== undefined ) ? options.loop : true;
this.videoElement.autoplay = ( options.autoplay !== undefined ) ? options.autoplay : true;
this.videoElement.src =  src;
this.videoElement.load();
....
}

**Comment by pchen66** [comment]
Good catch! Autoplay option was initially missing because it needs additional event dispatching handler to the control widget. I've added the autoplay support in v2-dev (f285e775246f3a7bdf7fb8308e324d5fd0e01ab4) and (f315aee45f0b606bb42dba01e549f3193e043412)
