### ISSUE TITLE
how can i manipulate the "output:console" 

### ISSUE THREAD

**Issue by nabilchen96** [pchen66/panolens.js#265]
i was successful to display xyz coordinate with const viewer = new PANOLENS.Viewer ({output: 'console'});
but I can't use these coordinates to insert into other html elements such as forms or popups, how do I do that?

**Comment by adam-sal** [comment]
I am also struggling with a similar need. I would like to use the coordinates captured from the console to add infospots by the user.

**Comment by lucychen0103** [comment]
@nabilchen96 @adam-sal does this thread help? https://github.com/pchen66/panolens.js/issues/245

**Comment by flyandi** [comment]
I added the position as event .. #299

**Comment by flyandi** [comment]
This is released in 0.12.1 now. https://github.com/pchen66/panolens.js/releases/tag/v0.12.1
