### ISSUE TITLE
Framerate and head-tracking lag

### ISSUE THREAD

**Issue by Japegrape** [pchen66/panolens.js#27]
Hey guys, loving this library. I just have one comment/concern:

When I load up a fairly large panoramic video and try to view it in cardboard mode, I often see framerates and thus head-tracking responsiveness lag considerably more than if I just build the experience myself. When I implement a simple Three.js sphere with Stereo Effect and Device Orientation Controls, then load up a <video> element into a <canvas> and use that canvas as a texture (exactly how you're doing it in PANOLENS.VideoPanorama.prototype.load), it runs buttery smooth with quick head-tracking and very high framerates on my test devices.

I'm not sure what's causing the slowdown, but it's preventing me from using this library in a very high-profile project I'm working on, which is a drag. Let me know if there's something I can do to speed up these framerates!

**Comment by pchen66** [comment]
Thanks to bringing this up. I loaded a 45MB mp4 video on mac book pro using chrome 51 but didn't observe framerate dropping or lagging in cardboard / stereo mode. Same with mobile safari, but I did notice dropping using Android device. What device were you testing on and which browser (desktop/mobile) were you using?

**Comment by Japegrape** [comment]
I was testing on both a Nexus 5X and a Nexus 6, so both Android. Desktop does look fine, so I guess it's just something causing a hangup on the Android version of Chrome...

If you have any ideas of what it might be, let me know!

**Comment by pchen66** [comment]
I disabled `antialiasing` by default in (dev)[https://github.com/pchen66/panolens.js/tree/dev] branch. It helps a bit, especially when you pause the video. Tested on Nexus 7 using Android 6. Let me know if it does the same for you.

**Comment by pchen66** [comment]
Closed #82
