### ISSUE TITLE
InfoSpot Display Error

### ISSUE THREAD

**Issue by RamenKebab** [pchen66/panolens.js#270]
I'm having a few problems with the infospots. They are properly displayed in Safari on MacBook, but in Chrome some of them appear as black squares instead of png icons. Besides that, while in 4 panoramas the infospots are displayed, for one of them the infospot doesn't appear as long as I don't create second one in the same panorama. I am not sure this second issue is because i am a beginner. But the browser issue is certainly puzzling. 

I am using panolens.min.js (master) and three.min.js. However, I would like to have highly customized infoSpots. I've seen here that solutions were usually in the infospot.js. Should I just call it in my html alongside panolens.min.js ? I would really appreciate your help, I am stuck.. (I attached a screenshot and my JS script.)

![blackinfo](https://user-images.githubusercontent.com/75453761/101114474-d9079a80-35e1-11eb-84da-c21285743355.jpg)

[JSscript.docx](https://github.com/pchen66/panolens.js/files/5640256/JSscript.docx)

**Comment by xuanvan229** [comment]
@RamenKebab . This was a pain point for me. I found a solution. 
<img width="1279" alt="Screen Shot 2020-12-04 at 09 50 25" src="https://user-images.githubusercontent.com/22408713/101116054-f1de7300-3616-11eb-930e-82e6ad0f98c7.png">

**Comment by xuanvan229** [comment]
@RamenKebab . This was a pain point for me. I found a solution.

<img width="984" alt="Screen Shot 2020-12-04 at 09 54 46" src="https://user-images.githubusercontent.com/22408713/101116126-15a1b900-3617-11eb-98a4-c57f1f7c33ef.png">

**Comment by xuanvan229** [comment]
@RamenKebab . This was a pain point for me. I found a solution.
<img width="911" alt="Screen Shot 2020-12-04 at 09 57 59" src="https://user-images.githubusercontent.com/22408713/101116201-3964ff00-3617-11eb-8db3-6be35bdc59f6.png">

**Comment by RamenKebab** [comment]
Thank you @xuanvan229 ! Could you please elaborate about the solution and how/**where** to integrate your code ?

**Comment by xuanvan229** [comment]
@RamenKebab  When you add infospot image. You should add some random text after link of the image like

`https://example.com/infospot.png?v=123456789`.

That helps your image not cache.

**Comment by RamenKebab** [comment]
@xuanvan229 Thank you !

**Comment by lucychen0103** [comment]
@xuanvan229 So the "123456789" in https://example.com/infospot.png?v=123456789 doesn't change the link? Why do you need the ${Date.now() in ${Date.now() + Math.floor(Math.random() * 100000)}?

**Comment by xuanvan229** [comment]
@lucychen0103  Yes, the "123456789" doesn't change the link. 
https://stackoverflow.com/questions/728616/disable-cache-for-some-images

**Comment by jediborre** [comment]
Make it base64 the image and the bug is gone!

**Comment by xuanvan229** [comment]
@jediborre You right. Just use base64 image.
