### ISSUE TITLE
Help for make a map situation with 360 visit with Panolens.js

### ISSUE THREAD

**Issue by RIFFIOD** [pchen66/panolens.js#271]
Hi, i'm french and i'm starting to code in Javascriopt. I'm biology teacher in highschool.
I'm using Panolens.js for make a visite of our high school like this 
[https://riffiodr.pagesperso-orange.fr/Panolens/examples/Visite_College09.html](https://riffiodr.pagesperso-orange.fr/Panolens/examples/Visite_College09.html)
 and I'm trying to inser a small map at the corner of the highscool for see where we are. I have made all the pictures [()with](https://riffiodr.pagesperso-orange.fr/Panolens/examples/Images/PlanCollege01.png) the différent position, but I don't know how I can make a "addListenEvent" for get the right picture à right time.

I'm realy sorry for my bad English.

Can you help me ?
Thanks

##### Description

Describe the bug or issues with as much detail as possible. It'd be nice to have a code snippet or screenshots to better illustrate the problems.

Please also include a live example if possible. You can start from these templates:

* [codepen](https://codepen.io/pchen66/pen/YNXEQW) (dev branch)

##### Panolens version

- [ ] Master
- [ ] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by RIFFIOD** [comment]
Hello,
I have find by myself a solution.
I have us uuid.
thanks to have made Panolens.js.

**Comment by flyandi** [comment]
Closing this.
