### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by flyandi** [pchen66/panolens.js#273]
I see many issues / bug fixes / MR's and past commit was years ago.

I am happy to take it over as it powers a few of my projects and I have to do custom builds at the moment.

**Comment by buntysala** [comment]
Did you hear back from Ray?

**Comment by flyandi** [comment]
nope

**Comment by bryancsc-umich** [comment]
@flyandi, did you hear back?

**Comment by lucychen0103** [comment]
I heard back by emailing Ray directly. I'll link him to this post.

**Comment by pchen66** [comment]
Sorry guys I wasn't tracking my notifications and thanks @lucychen0103 for letting me know. @flyandi please take good care of the project! :)
