### ISSUE TITLE
Panorama link number 2 with custom image has bug

### ISSUE THREAD

**Issue by habibieamrullah** [pchen66/panolens.js#279]
Hello,

If I do this: 

panorama1.link( panorama1, new THREE.Vector3(somecoordinates ), 400, 'asset/textures/1941-battle-thumb.png' );
panorama1.link( panorama2, new THREE.Vector3(somecoordinates), 400, 'asset/textures/1941-battle-thumb.png' );
panorama1.link( panorama3, new THREE.Vector3( somecoordinates), 400, 'asset/textures/1941-battle-thumb.png' );

The second link will be gone, not showing anything, only 1st and 3rd are working.

There is no problem if we don't use custom image like panorama1.link( panorama2, new THREE.Vector3(somecoordinates));

My workaround for now is to duplicate the second panorama link, it works temporarily, until we can have the bugfix.

panorama1.link( panorama1, new THREE.Vector3(somecoordinates ), 400, 'asset/textures/1941-battle-thumb.png' );
panorama1.link( panorama2, new THREE.Vector3(somecoordinates), 400, 'asset/textures/1941-battle-thumb.png' );
panorama1.link( panorama2, new THREE.Vector3(somecoordinates), 400, 'asset/textures/1941-battle-thumb.png' ); //intentionally duplicated
panorama1.link( panorama3, new THREE.Vector3( somecoordinates), 400, 'asset/textures/1941-battle-thumb.png' );

**Comment by habibieamrullah** [comment]
Same thing also true with Infospot.

**Comment by habibieamrullah** [comment]
I found out that this feature is somehow buggy if we use image files... So I tried to decode my custom infospot image files to Base64 images using this awesome website: https://www.base64-image.de/

**Comment by leonexcc** [comment]
Maybe this is the problem: https://github.com/pchen66/panolens.js/issues/263#issuecomment-719479055

I had this problem even with data URIs

**Comment by habibieamrullah** [comment]
I was trying to build a visual editor for making 360 tours based on this Panolens... check it out here: https://3sixty.webappdev.my.id/

**Comment by habibieamrullah** [comment]
In my case, I make a bunch of arrays containing base64 image data of some custom hotspot icons and I used them without problem... like this: https://github.com/habibieamrullah/3Sixty-WebTour-Maker/blob/main/resources/panotemplate/imagedata.js

**Comment by flyandi** [comment]
Hm.. I run up to 20-30 images linked and I have not encountered his issue. perygon.com/flyandi

Care to share how you implemented it?

I wrote a small caching implementation that pre-loads all objects but doesn't mount them.

```
    load: function(id) {
        const image = this.cache[id];
        if (!image) {
            return;
        }

        const imageSource = image.variations[ImageVariations.LowEightK];
        this.cache[id]._pano = new PANOLENS.ImagePanorama(imageSource);
        this.cache[id]._planet = new PANOLENS.ImageLittlePlanet(imageSource);
        this.cache[id]._pano.addEventListener('progress', this.onProgress);
        this.cache[id]._pano.addEventListener('enter', this.onEnter);
        this.cache[id]._mounted = false;
    },
```

It will mount them only if the user selected an image.

So maybe that helps to avoid any memory issues.
