### ISSUE TITLE
IE11 bug

### ISSUE THREAD

**Issue by andymcpherson** [pchen66/panolens.js#28]
Panolens fails to load images in IE11.
Steps to reproduce: open any example in IE11. An InvalidateStateError is thrown.
Cause: IE11 incorrectly throws this error when an XMLHttpRequest object has the responseType set before the request is opened. 

Fix: ImageLoader.js
Swap lines 86 & 87 so that the request is opened before the responseType is set.

**Comment by pchen66** [comment]
Thanks for catching this. I didn't touch IE or legacy browser support much. I've changed the order in v2-dev (f9ee1fc062e1379ccbf44f19b063f51dd2b34494) Feel free to submit a PR if you find anything useful in the future. 😃
