### ISSUE TITLE
ReactJS Support

### ISSUE THREAD

**Issue by ahsanihsan** [pchen66/panolens.js#292]
##### Description

Hi, I have been looking around for support of such components for a long time and I guess this is the only way to go for. I can also use react-three-fiber, But I would have to create the whole thing from scratch, because I am creating an engine to edit the hotspots, drag and drop on the screen. How will I be able to get the support for panolens.js in ReactJS?

**Comment by flyandi** [comment]
I am using it with react right now ... 

in index.html just add the three and panolens...

```
    <script src="%PUBLIC_URL%/static/js/three.min.js"></script>
    <script src="%PUBLIC_URL%/static/js/panolens.min.js"></script>
   ...
   <script>
      window.PANOLENS = PANOLENS;
      window.THREE = THREE;
    </script>
```

then in my component I just expose it via 

```
const PANOLENS =window.PANOLENS;
```

then u can just use like:

```
this.instance = new PANOLENS.Viewer({
            container: document.getElementById('scene'),
            controlBar: false,
            renderer: new THREE.WebGLRenderer({
                alpha: true,
                antialias: false,
                preserveDrawingBuffer: true,
            })
        });
```

Let me work on a hook based component to simplify stuff.

**Comment by ahsanihsan** [comment]
Yes I got it, it's working as well. I also cloned the whole repo and I am using the bare source code of the repo. One thing if you could help me out with that? I am trying to create draggable hotspots/infospots. Can you guide me how can I achieve that ?

**Comment by flyandi** [comment]
U have full access to all the threejs api.  For example you can add a custom object to the scene and use DragControls to move it within the 3D space https://threejs.org/docs/#examples/en/controls/DragControls.

I am running perygon.com and I use a lot the direct ThreeJS API for spheric rotation, etc. Not everything is solved with Panolens directly but the nice thing is that Ray kept it Panolens at an abstraction level.

The `InfoSpot` is a ThreeJS sprite in the end and you can just add it to a draggable independent of the scene.

https://threejs.org/docs/#examples/en/controls/DragControls

**Comment by TuanAnh266** [comment]
@flyandi Hi sir, im having a panorama-project, i tend to make it done by using ReactJs, but i have a lot of issues, i have taken a look into Perygon.com and im really impressed by your product. Can you with help me with my project ? Thanks in advance 👯

**Comment by hungvo2010** [comment]
@flyandi Hi sir, can you provide an example about using Panolens with React Hooks?
