### ISSUE TITLE
Add panorama.link onClick

### ISSUE THREAD

**Issue by marcusdevon** [pchen66/panolens.js#300]
I'm trying to make an editable panorama/360photo where I can put or ADD arrow buttons(panorama.link) and then link it to another panorama pic, but somehow I couldn't find making dynamic button in documentation. 

What I want is:
-Display the new panorama.link/arrowbutton on the 360photo when I click it
-get the coordinates.
-select a photo to link it on the button<<not a problem tho.

Is there any way to do this? or have better way to do it?
I tried adding an eventlistener onClick that will call a function like this:

>   function onClick ( event ) {
>      //Test add
>       panorama.link( panorama2, new THREE.Vector3( -2302.98, 358.27, -4414.74 ) );
> 
>       viewer = new PANOLENS.Viewer({output:'console'});
>       viewer.add( panorama);
>       
>    }

Any other free 360viewer library that can do it?

**Comment by flyandi** [comment]
like static overlays? or within the scene? - U can place any kind of button within the scene - just make it an InfoSpot and  assign an icon and link it out.

For overlay just fix or absolute position your buttons above the scene with an higher zIndex.

**Comment by marcusdevon** [comment]
> like static overlays? or within the scene? - U can place any kind of button within the scene - just make it an InfoSpot and assign an icon and link it out.
> 
> For overlay just fix or absolute position your buttons above the scene with an higher zIndex.

Thanks for the quick response. Though I think I did what I wanted already.
I'll comeback and close this after testing different things to check if I have an issue.
