### ISSUE TITLE
where is examples sources in project 

### ISSUE THREAD

**Issue by dengyuanke** [pchen66/panolens.js#302]
Hi,I want to learn demo in this page https://pchen66.github.io/Panolens/#Example,I download this project,but i don't found that page examples.Where is the source code of the project? Thanks

**Comment by flyandi** [comment]
You just select "View Source Code" from your browser or find them here: 

https://github.com/pchen66/pchen66.github.io/tree/master/Panolens/examples

**Comment by dengyuanke** [comment]
> You just select "View Source Code" from your browser or find them here:
> 
> https://github.com/pchen66/pchen66.github.io/tree/master/Panolens/examples

Thanks!
