### ISSUE TITLE
Large Panorama Not Loading Properly...

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#31]
Hi,

I have tried to load [Image](https://upload.wikimedia.org/wikipedia/commons/e/e7/Piazza_della_Rotonda_Rome_panoramic_view_360_9852px.jpg) but seems like camera position is set far up then regular position or something else... not sure about this... May I now How can I load this type of large panorama image?

**Comment by pchen66** [comment]
`PANOLENS.ImagePanorama` takes only equirectangular (width:height exactly 2:1). The image is for cylinder projection, which is not currently supported. The support may come later though.
