### ISSUE TITLE
Creating a second type of InfoSpot? 

### ISSUE THREAD

**Issue by AlchemistArchitect** [pchen66/panolens.js#313]
How can I make a second type of InfoSpot in panolens.js? Besides the nice default InfoSpot, I need another one that does not scaleUp and doesn't turn the cursor into a pointer.

I am using a custom png image to show together the icon and the name of the place. As I need three names in three different alphabets I am not using addHoverText. I instead made a png that combines them all. But all the transparent square space around became clickable and the info windows appear before coming over the icon.
I wanted to separate them into two different png, name and icon.
<img width="346" alt="Capture d’écran 2021-03-08 à 16 17 25" src="https://user-images.githubusercontent.com/80217903/110341150-52bc8380-802a-11eb-86e4-db20708b64ba.png">

You can try the panorama and see the code : www.dreampixels.world/virtual_tour.html
If you wish ti see, this is the main page: http://dreampixels.world/

I am quite a beginner in coding. I'm an architect in Ph.D. experimenting with digital tools. This is what I could make following tutorials and forums.. So I would greatly appreciate any help you can give...

##### Panolens version

- [X ] Master

##### Browser

- [] All of them
- [ X] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ X] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by AlchemistArchitect** [comment]
Found the solution. Instead of creationg a whole new type of infospot, I've targeted all those infospots for which I wanted to disable the cursor change into pointer. I cancelled onHoverStart and End events by targeting the names of the png images that i use for infospots. If they have certain letters they don't apply, if not they do. Added this into panolens.js line 1995.

 var res = imageSrc.slice(imageSrc.length - 6);
  			if(res == "en.png"){
  				console.log(true);}

                         else if(res == "gr.png"){
				console.log(true);}

                         else if(res == "ot.png"){
				console.log(true);}
                         else {
  		this.addEventListener( 'click', this.onClick );
	        this.addEventListener( 'hover', this.onHover );
	        this.addEventListener( 'hoverenter', this.onHoverStart );
	        this.addEventListener( 'hoverleave', this.onHoverEnd );
		}

**Comment by flyandi** [comment]
I think we need to add an un-opinioned InfoSpot class to the library. This issues comes up quiet often.
