### ISSUE TITLE
Inserting an Iframe inside panolens?

### ISSUE THREAD

**Issue by Albneto** [pchen66/panolens.js#315]
Hello,

I've been trying to insert an iframe (or at least a div) inside the 3D space of panolens, but I can't seem to find a way to do so. I did see [this example](https://github.com/pchen66/pchen66.github.io/blob/master/Panolens/examples/panorama_infospot.html) with the div holding a video and description, but it's directly linked to an infospot. I would need that div to be always visible on a specific spot, and not necessarily be a video. How could I achieve this without needing an infospot to be hovered over?

**Comment by Albneto** [comment]
I managed to get the iframe by the hover of an infospot, but I can't fire the hover element manually, without passing the cursor over the specific infospot. Also, locking and turning away makes the infospot automaticly close the hoverElement. Is it possible to fire the hover event manually and keeping the image there?

**Comment by leonexcc** [comment]
The Pano Theater from the websites embedds youtube videos as an iframe: https://github.com/pchen66/pchen66.github.io/tree/master/PanoTheater (see here: https://pchen66.github.io/PanoTheater/)
