### ISSUE TITLE
Does it support Angular? 

### ISSUE THREAD

**Issue by promailson** [pchen66/panolens.js#317]
How will I be able to get the support for panolens.js in Angular 11?

**Comment by flyandi** [comment]
technically yes - as it's normal JS code .. I use it in a React app - u need to figure out how to get it imported to your class. 

In React I include the file in the main document and then expose the handler on `window.` -  in my class I just invoke it via `window.` which works perfectly. 

If u end up writing a custom library handler for Angular would be awesome if u could share it. I am putting together one for React right now.
