### ISSUE TITLE
Working example of createVideoElement and createVideoTexture?

### ISSUE THREAD

**Issue by Braedencraig** [pchen66/panolens.js#321]
Just trying to get the classic floating cube rendered with video as texture and it just ain't working! Anyone have any working examples of this with Panolens?

media = new PANOLENS.Media();
testVideo = media.createVideoElement();
testVideo.src = video;

This works great, but I dont know how to instantiate the createVideoTexture

**Comment by furryronin** [comment]
Hey @Braedencraig,

I managed to get a single video mapped to one side of a cube in a scene for a standup sign based off the three.js video texture example. 

I have a HTML5 video element hidden in the background that auto plays on load:

`<video id="thevideo" src="LINKTO.MP4FILE" autoplay loop muted playsinline style="display: none;"> No video support in this browser.</video>`

Then I map that video to the face of the object and position it in the scene. It's a bit of a longform version of the code, but I used:

`        
        //set a background colour
        let videoBackground = 'black';
        
        //the video element above
        video = document.getElementById( 'thevideo' );
        
        //creating the cube
        videoImage = document.createElement( 'canvas' );
        videoImage.width = 800;
        videoImage.height = 1800;
        videoImageContext = videoImage.getContext( '2d' );
        videoImageContext.fillStyle = videoBackground;
        videoImageContext.fillRect( 0, 0, videoImage.width, videoImage.height );
        
        //applying the video texture
        videoTexture = new THREE.Texture( videoImage );
        videoTexture.minFilter = THREE.LinearFilter;
        videoTexture.magFilter = THREE.LinearFilter;
        
       let movieMaterial = new THREE.MeshBasicMaterial( { map: videoTexture,side:THREE.FrontSide } );

        // the geometry on which the movie will be displayed;
        //movie image will be scaled to fit these dimensions.
        let movieGeometry = new THREE.PlaneGeometry( 1300, 2700);
        let movieScreen = new THREE.Mesh( movieGeometry, movieMaterial );
        
        //position in scene
        movieScreen.position.set(3800, -100, -3493.52);
        //add to scene
        panorama.add(movieScreen);`

**Comment by Braedencraig** [comment]
THIS RULES @furryronin thank you so much! Exactly what I needed!

**Comment by perfectpluto** [comment]
@furryronin 

Where is this "video" being used in the rest of your code? I presume it was a typo or was that part of the code omitted for brevity?

Could you please let me know? This is what I am actually trying to do - https://github.com/pchen66/panolens.js/issues/335 but am clueless on how to go about it.. I have to get a Texture displayed on top of an ImagePanorama. 

Thanks for your help..

**Comment by furryronin** [comment]
@perfectpluto 

Sorry! New baby, haven't been able to get here much.

Looks like the above example is missing a couple of functions, whole thing should be:

I managed to get a single video mapped to one side of a cube in a scene for a standup sign based off the three.js video texture example.

I have a HTML5 video element hidden in the background that auto plays on load:

`<video id="thevideo" src="LINKTO.MP4FILE" autoplay loop muted playsinline style="display: none;"> No video support in this browser.</video>`

Then I map that video to the face of the object and position it in the scene. It's a bit of a longform version of the code, but I used:

```
<script>


let video

//video render functions
function animate() {
    requestAnimationFrame( animate );
    render();		
    if(video){
      video.play();
    }
}
function render() {	
  if(video){
    if ( video.readyState === video.HAVE_ENOUGH_DATA ) 
    {
      videoImageContext.drawImage( video, 0, 0 );
      if ( videoTexture ) 
        videoTexture.needsUpdate = true;
    }
  }
}
	//set a background colour
	let videoBackground = 'black';

        video = document.getElementById( 'signvideo' );
        videoImage = document.createElement( 'canvas' );
        videoImage.width = 800;
        videoImage.height = 1800;
        videoImageContext = videoImage.getContext( '2d' );
        videoImageContext.fillStyle = videoBackground;
        videoImageContext.fillRect( 0, 0, videoImage.width, videoImage.height );
        videoTexture = new THREE.Texture( videoImage );
        videoTexture.minFilter = THREE.LinearFilter;
        videoTexture.magFilter = THREE.LinearFilter;
        var movieMaterial = new THREE.MeshBasicMaterial( { map: videoTexture,side:THREE.FrontSide } );

        // the geometry on which the movie will be displayed;
        // movie image will be scaled to fit these dimensions.
        var movieGeometry = new THREE.PlaneGeometry( 1300, 2700);
        var movieScreen = new THREE.Mesh( movieGeometry, movieMaterial );
        movieScreen.position.set(3800, -100, -3493.52);
        panorama.add(movieScreen);

</script>
```

**Comment by furryronin** [comment]
But basically I call an Onload event that calls the animate function - [ animate(); ] that uses video to overlay the video frame by frame to the moviescreen.

Does that help?
