### ISSUE TITLE
Object Loader in infospot

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#33]
I want to load Object in infospot.

for example load object when user hover on infospot and display object in popup

so I have tried below code

`

				var time = new Date().getMilliseconds();
				var aid = "a" + time;
				var iid = new PANOLENS.Infospot(350, PANOLENS.DataImage[type]);
				iid.playerid = aid;
				infospoteventlistner.push(aid);
                var elementId = this.randerContainer(counter);
				document.getElementById(elementId).innerHTML = player.getObjectHtml( useruploadbasepath + screenData.typevalue,screenData.position);
				iid.addHoverElement(document.getElementById(elementId));
				iid.position.set(screenData.position.x, screenData.position.y, screenData.position.z);

				
			
		
			var manager = new THREE.LoadingManager();
				manager.onProgress = function ( item, loaded, total ) {

					console.log( item, loaded, total );

				};

				var texture = new THREE.Texture();

				var onProgress = function ( xhr ) {
					if ( xhr.lengthComputable ) {
						var percentComplete = xhr.loaded / xhr.total * 100;
						console.log( Math.round(percentComplete, 2) + '% downloaded' );
					}
				};

				var onError = function ( xhr ) {
				};

				var loader = new THREE.OBJLoader( manager );

				loader.load( url, function ( object ) {

					object.traverse( function ( child ) {

						if ( child instanceof THREE.Mesh ) {

							child.material.map = texture;
							child.material.transparent = true;
							var object = new THREE.Mesh( child.geometry, child.material);
							

						}

					} );

					
					viewer.addUpdateCallback( function () {

				        object.rotation.y += 0.01;

				      } );
					object.position =position;
				return object;
				}, onProgress, onError );
				
`

I am not able to see any Object

Can Anyone Help me regarding this?

**Comment by smitshah81** [comment]
in otherway i am tring to achieve 

http://pchen66.github.io/Panolens/examples/panorama_basic.html

in image panorama.How can I do that?

**Comment by pchen66** [comment]
Here's a basic example that might help you achieve what you want. [http://codepen.io/pcehn66/pen/vKvWQV](http://codepen.io/pcehn66/pen/vKvWQV) If it's rendering on different container (other than panorama itself), you have to create another renderer, camera, and scene to render on that particular element you want. One thing to note is that the hovering element isn't the one you created in the first place (to avoid browser reflow or layout change), you can call `infospot.element` to get the dom element and append `renderer.domElement` to it.

**Comment by smitshah81** [comment]
Thanks :) It Works...

**Comment by smitshah81** [comment]
Hi,

Infospot Object is not Displaying in Cardboard/Stereoscopic view.Any Solution?

**Comment by pchen66** [comment]
yes, that's because the dom element in the stereo/cardboard mode is cloned. You can attach event listener when the mode is changing to dual screen and re-enable rendering after these side-by-side elements being created.

**Comment by dmw4176** [comment]
> Here's a basic example that might help you achieve what you want. http://codepen.io/pcehn66/pen/vKvWQV If it's rendering on different container (other than panorama itself), you have to create another renderer, camera, and scene to render on that particular element you want. One thing to note is that the hovering element isn't the one you created in the first place (to avoid browser reflow or layout change), you can call `infospot.element` to get the dom element and append `renderer.domElement` to it.

pchen66 instead of hovering on the info spot to pop up content can you make it an "onclick" event? I tried but it is not working. Also can you add animated gifs on top of the pano viewer?
