### ISSUE TITLE
Set initial rotation angle/yaw?

### ISSUE THREAD

**Issue by herzogf** [pchen66/panolens.js#35]
Hi,

Is it possible to set the initial rotation angle / yaw as it is possible with google VR View and its "start_yaw" parameter (https://developers.google.com/vr/concepts/vrview-web)?
I tried to rotate via the control but this didn't work the way I tried it:

```
viewer.getControl().rotateLeft(-90 * Math.PI / 180);
viewer.getControl().update();
```

(This worked when putting an alert("hello") before it so it seems I'm struggling with timing problems there)

**Comment by epos** [comment]
Same problem here. Solved it by changing the angle inside the panorama load event. But that's akward.

            panorama.addEventListener('load', function() {
                if(viewer.getControl().getAzimuthalAngle()==0) {
                    viewer.getControl().rotateLeft(Math.PI);
                    viewer.getControl().update();
                }
            });

**Comment by pchen66** [comment]
Another approach is to focus on a specific vector when `enter-fade-start` event fires on panorama. Instead of finding yaw/pitch, locate the infospot position that you want to see initially and call `viewer.tweenControlCenter(vector [, duration] [, easing])`. Here's an example: [Initial LookAt](https://codepen.io/pchen66/pen/LLgxME)

**Comment by huxiyu** [comment]
when control is DeviceOrientationControls.  How to set initial lookat?

**Comment by Dok11** [comment]
@epos have you example with possible to set looking center as absolute values?
For example, I want change `y` of looking center by some event on page.

`tweenControlCenter` require `THREE.Vector3` object - it's really the only opportunity for my issue?

**Comment by qria** [comment]
Here is my solution after researching a bit:

```

        function setGaze (target) {
            /**
            * Set line of sight for panolens camera.
            *
            * Panolens uses `THREE.OrbitControls` as a way to control the camera
            * so normal `THREE.PerspectiveCamera.rotation` does NOT work.
            *
            * @param  {THREE.Vector} target - Target to look at.
            */

            const { x, y, z } = target.normalize();
            viewer.camera.position.set(x, -y, -z);
        }
```

However I have yet to figure out why x coordinate should not be reversed.

**Comment by walidmahade** [comment]
https://codepen.io/pchen66/pen/LLgxME

Any idea why does it jump when changing Panorma ? @pchen66
