### ISSUE TITLE
add a normal image to hide camera stand

### ISSUE THREAD

**Issue by CasperWind** [pchen66/panolens.js#370]
im working on a virtual tour with panolens.js and i want to hide the camara stand with a logo.

i have tried to hide it with a infospot but it does not look good.

i cant find enything in the documentation about a normal image. Maybe it's me who overlooks something

##### Panolens version

- [x] Master
- [ ] Dev

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by henriod** [comment]
I was able to achieve this by editing the image in photoshop before using it in panolens. it required converting the image into 6 cube images so that the stand edit become easy.

**Comment by CasperWind** [comment]
sorry for the late response. 

i have tryed the same thing at it works. :_)
