### ISSUE TITLE
How to use Panolens in Next JS

### ISSUE THREAD

**Issue by irwansyafani** [pchen66/panolens.js#384]
##### Description

How to use Panolens in Next JS, I do not have any reference to implement
can someone help?

##### Panolens version
- [x] Master
##### Browser
- [x] Chrome
##### OS
- [x] macOS
```
Device: Mac M1
```

**Comment by e-pacciani-developer** [comment]
You can install the npm package and use it in the React template of the page you are making. I would make an hook named usePanolens passing the HTML ref of the element to the hook and configuring there all the options to create the panorama.

**Comment by irwansyafani** [comment]
Alright, thank you @e-pacciani-developer

**Comment by flyandi** [comment]
This is what I do ..


```import { Viewer } from "panolens";
import THREE from "threejs";
import {useRef, useEffect} from "react";

const usePanolens = ({ width = "100%", height = "100%", options }) => {

    const instance = useRef();
    useEffect(() => {
        const container = instance.current;
        new Viewer({
            container,
            controlBar: false,
            renderer: new THREE.WebGLRenderer({
                alpha: true,
                antialias: false,
                preserveDrawingBuffer: true,
            }),
            ...options,
        })

    });

    return (
        <div style={{width, height}} ref= {instance} />
    )
};
```
