### ISSUE TITLE
Display errors on load on iOS

### ISSUE THREAD

**Issue by nicmare** [pchen66/panolens.js#42]
On my iPhone 6S and 7 i noticed some weird display errors when i open my site where i embedded the panolens iframe. I need to reload the page several times until the error is gone. It looks like it is zoomed in very far:
![pano_error](https://cloud.githubusercontent.com/assets/898582/18865848/8efb0214-849d-11e6-8a75-985ecac86cc5.jpg)
any idea how to fix this issue?

**Comment by nicmare** [comment]
LInk to page: http://offenblen.de/360-grad-fotografie/

**Comment by zcherries** [comment]
I also had that issue but was able to get around it by setting a listener to the iframe onload and then setting the width and height at that point to 100%.

**Comment by pchen66** [comment]
I couldn't reproduce on my end. Currently you're using r2. Please update to the latest to see if you experience the same issue. Please reopen if it happens still.
