### ISSUE TITLE
How to use Key control?

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#43]
Hello,

I want to use Key control but it is not working;
**N.B:** I have checked onKeydown event of Orbitcontrol but it is not working.If there is any example then it is much appreciated.

**Comment by AloudmyRC** [comment]
hi, I use Keyboard.js, it's work
https://github.com/RobertWHurst/KeyboardJS/tree/master

**Comment by pchen66** [comment]
Arrow key controls are now being supported. Closed #82
