### ISSUE TITLE
Panorama "infospot focus demo" not working when it is linked to video panorama

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#44]
Hello ,

When we connect two panorama i.e. image and video panorama using [infospot focus demo](http://pchen66.github.io/Panolens/examples/panorama_infospot_focus.html) somehow it is not working , any hint?

**Comment by pchen66** [comment]
Try again with the [example](http://pchen66.github.io/Panolens/examples/panorama_infospot_focus.html) with linking to a `VideoPanorama`. Please reopen if you still experience the issue.
