### ISSUE TITLE
Does panolens have a "dwelling" animation script?

### ISSUE THREAD

**Issue by donblaauw** [pchen66/panolens.js#48]
The "dwelling time " is the time the center cursor/crosshairs is hovering over a hotspot. After a predefined number of seconds the system will "see" the hovering as a touch/mouseclick and proceeds to follow the action belonging to that touch/mouseclick. 
I would like to have this dwelling made visible. Ray talks about an option  three.js already addresses this thing. But how can this be used within panolens? And would there be several presets to choose from?

**Comment by smitshah81** [comment]
Hello,

I guess you want auto focus on hotspot after certain amount time period and yes I guess Ray has implimented this option in "[infospot focus](http://pchen66.github.io/Panolens/examples/panorama_infospot_focus.html)" script

**Comment by donblaauw** [comment]
No. The auto focus is not the aim. In my game kids would have to look for certain objects hidden in the 360°   After "seeing" something in the image they will be hovering over that spot  I want them to notice that the system is going to focus on that spot. 

With an animation. Like a circle scaling zero or a pie chart filling up (clock)

Vriendelijke groeten,
Don Blaauw

studio No More Mondays
+316 24581166

**Comment by pchen66** [comment]
Yes, it's coming out soon :)

**Comment by pchen66** [comment]
Please see the current dwell animation example: [Panorama Reticle Example](http://pchen66.github.io/Panolens/examples/panorama_reticle.html) 
More detail please see: [API documentation](http://pchen66.github.io/Panolens/docs/PANOLENS.Reticle.html)
