### ISSUE TITLE
Any Example using VRCJS.SpriteText ??

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#50]
Hello,
I have tried using **PANOLENS.SpriteText** but got an error "panolens-player.js:9160 Uncaught TypeError: this.addText is not a function", can you please give me example which uses PANOLENS.SpriteText ?

**Comment by pchen66** [comment]
Sorry I haven't heard of VRCJS. Can you give me a scenario of usage?

**Comment by smitshah81** [comment]
My bad... Nervermind..got idea from [link](https://github.com/pchen66/panolens.js/issues/58)
