### ISSUE TITLE
window resize event is't work when container with classname 'panolens-container'

### ISSUE THREAD

**Issue by AloudmyRC** [pchen66/panolens.js#52]
## is't work:
`<div class="AAAA"></div>`
`viewer = new PANOLENS.Viewer({ container: document.getElementsByClassName("AAAA")[0],  });`

## work:

`<div class="AAAA panolens-container"></div>`
`viewer = new PANOLENS.Viewer({ container: document.getElementsByClassName("AAAA")[0],  });`
or
`<div class="panolens-container"></div>`
`viewer = new PANOLENS.Viewer({});`

**Comment by smitshah81** [comment]
I guess,That will definitely won't work because "panolens-container" class is pre-generated from [javascript](https://github.com/pchen66/panolens.js/blob/master/build/panolens.js#L7088) and canvas is append to this class.try with some other class or alter this class to your desired class.

**Comment by gillesgoetsch** [comment]
To clarify the behavior:

Panolens resizes the canvas properly if no container is set.
When a custom container is used, the canvas does NOT resize to the custom containers dimensions.

A workaround is to add the class `panolens-container` to the custom container.

**Comment by pchen66** [comment]
Closed #82 
Similar issue #80
