### ISSUE TITLE
Multiresolution Panoramas??

### ISSUE THREAD

**Issue by smitshah81** [pchen66/panolens.js#53]
Hello,

How to do Multiresolution Panoramas like [krpano](https://krpano.com/docu/multires/) , Can I request add this feature in panolens?

**Comment by pchen66** [comment]
Yes, it's part of the roadmap but no clear estimation at this point

**Comment by Avatarchik** [comment]
Do you plan to support this format?
https://pannellum.org/documentation/overview/
