### ISSUE TITLE
Safari will crash and reload on IOS

### ISSUE THREAD

**Issue by zhangshuzhen** [pchen66/panolens.js#55]
This is my test url.
http://qa.developer.163.com/house/pano/netpano/panolens.shtml

You can open it in your safari on iphone. Click screen to change spherepano. The safari will crash and reload after about ten times to change.

Hope you can understand what I say. Thank you.

**Comment by donblaauw** [comment]
LOL :-)

**Comment by donblaauw** [comment]
werkte toch al niet compleet.. de "onze" is de betere vooralsnog.. zoveel verder zeg! Hoera
