### ISSUE TITLE
Multiple hotsposts

### ISSUE THREAD

**Issue by oneshot-nc** [pchen66/panolens.js#56]
Hello.

How to add multiple hotspot links in each panorama to create "stories" ?

Thanks.
Pierre

**Comment by Strae** [comment]
With "stories" you mean something like a tour?
I guess you're looking for panorama linking ( http://pchen66.github.io/Panolens/examples/panorama_linking.html )

**Comment by oneshot-nc** [comment]
Yes, like a tour.

On your example, only one hotspot is possible.

**Comment by Strae** [comment]
mmmh nope. in the second photosphere there are 2 hotspots (look in the sky and then left)

The method shown in the examples use the built-in method of panorama linking, however, if you need more control you can just add the hotspot and react to the click event.

Sorry if I cant get deeper, but i switched to a-frame library so I dont know this one good

**Comment by pchen66** [comment]
Yes, you can create multiple hotspots. Thanks for explaination @Strae !
