### ISSUE TITLE
SpriteText Stroke

### ISSUE THREAD

**Issue by EdoB** [pchen66/panolens.js#58]
Is there a way to remove the black stroke?

**Comment by pchen66** [comment]
Hi, can you take a screenshot for me to understand the issue better?

**Comment by EdoB** [comment]
Hi! This is a SpriteText created with:
`let stext = new PANOLENS.SpriteText(lorem, 1500, 0xffffff);`

Is there a way to remove the black stroke around each character?

The problem is that as you zoom back the stroke starts to blend poorly.

<img width="600" alt="screen shot 2017-02-21 at 11 02 10" src="https://cloud.githubusercontent.com/assets/14101383/23160108/7dd28538-f825-11e6-9f50-3a1e3a16d2e6.png">
<img width="310" alt="screen shot 2017-02-21 at 11 08 25" src="https://cloud.githubusercontent.com/assets/14101383/23160305/420dc412-f826-11e6-85b1-e2fb6872b18e.png">
<img width="147" alt="screen shot 2017-02-21 at 11 08 45" src="https://cloud.githubusercontent.com/assets/14101383/23160306/420e669c-f826-11e6-8e2c-3a4d7747ee39.png">

Thanks!
