### ISSUE TITLE
Cardboard mode broken with newer three.js

### ISSUE THREAD

**Issue by jhall39** [pchen66/panolens.js#59]
Using three.js revision 84, only the left eye for cardboard mode renders, the right eye area is completely black. If I use revision 78, same as the one in the examples, then both eyes work.

**Comment by pchen66** [comment]
Yes, there's a change in how the buffer arrtibutes calculates length vs count from r80 to r81. I have updated in the dev branch to fix this issue. See [examples](http://pchen66.github.io/Panolens/#Example) which uses three js r84 now
