### ISSUE TITLE
Incorrect aspect ratio

### ISSUE THREAD

**Issue by matthew-dean** [pchen66/panolens.js#61]
When I use the imageloader and load an image, the image is badly skewed (super tall). Changing the camera's FOV doesn't change things. Is there any way to get Panolens to preserve aspect ratio?

(Side note: how do you turn off mousewheel zoom?)

**Comment by pchen66** [comment]
Hi, currently panolens supports 2:1 (width:height) ratio image only. In the future it might start to support multi-resolution and partial panorama. 

To turn off mousewheel zoom:
```
var viewer = new PANOLENS.Viewer();
viewer.OrbitControls.noZoom = true;

or

viewer.control.noZoom = true;    // if current control is using orbit control
```
