### ISSUE TITLE
Open bigger pano

### ISSUE THREAD

**Issue by Silvering** [pchen66/panolens.js#64]
Hi! I have a 8192x4096 pano image. When I load the image I get this : 

https://digitalblend.io/echange/pano-bug.png

Any idea? Thanks!

EDIT: This issue happens with node webkit.

**Comment by joe434200** [comment]
I had load a pano image 10000 x 5000 , it is ok

**Comment by pchen66** [comment]
Any error or warning that you saw?

**Comment by pchen66** [comment]
Closed for now. Please reopen if you have more information.
