### ISSUE TITLE
Image Panorama - Sensor Control

### ISSUE THREAD

**Issue by dmzone** [pchen66/panolens.js#66]
Is there a param to start with Sensor Control by default?

**Comment by AloudmyRC** [comment]
hi, you can set the Sensor Control after creating the viewer.
`
viewer = new PANOLENS.Viewer();
viewer.enableControl(1);
`

**Comment by dmzone** [comment]
Actually I had to set it after adding a panorama on viewer.

`viewer.add(panorama);
    viewer.enableControl(1);`

**Comment by pchen66** [comment]
There will be exposed method to setup initial configuration soon
