### ISSUE TITLE
can not set the panorama.position? Or viewer.position?

### ISSUE THREAD

**Issue by joe434200** [pchen66/panolens.js#67]
I use panorama.position.set(x,y,z), but it doesn't work...

I just want to set the initial visual angle of the panorama, and which attr should I set ?

**Comment by iamkyleee** [comment]
This is what I did.

`this.viewer.getCamera().position.set(initX, initY, initZ)`
`this.viewer.getControl().update()`

**Comment by joe434200** [comment]
@iamkyleee thks , I'll try it
