### ISSUE TITLE
Infospots not responding to touch event on mobile correctly

### ISSUE THREAD

**Issue by imakatman** [pchen66/panolens.js#70]
When I touch an infospot on a touch device, the infospots don't function properly. 

For example: in one of your examples http://pchen66.github.io/Panolens/examples/panorama_infospot.html  when i touch the infospot on an iPhone (iPhone6+ & iOS10.3.1), it just fadesOut rather than showing the container with the corresponding content.

**Comment by pchen66** [comment]
Thank all for reporting. I'll take a deeper look into this.

**Comment by pchen66** [comment]
This should be fixed with https://github.com/pchen66/panolens.js/commit/262d81ad4a440e5d2d152ad80c0f31580a85f966 ( #71 ). Please reopen if you still experience the issue. Tested with iOS10.3.2 + Chrome 58.0/ Firefox7.5 / Safari 10.0.
