### ISSUE TITLE
Changing Infospot icon to image 

### ISSUE THREAD

**Issue by LouGriffith** [pchen66/panolens.js#73]
Hi, 
I am loving this but was curious if it were possible to replace the infospot with a custom image? Also would it be possible to have a container replace the infospot instead of it appearing on hover. 

Thanks,
~ Lou

**Comment by pchen66** [comment]
Yes to your first question. You can load image you want by specifying image source when initiating an infospot with proper scale based on where you put it. Take a look at this [example](https://codepen.io/pchen66/pen/dRYNNG) and [api documentation](http://pchen66.github.io/Panolens/docs/PANOLENS.Infospot.html)

As for second question, currently it only supports on hover.

**Comment by LouGriffith** [comment]
Thank you!!!
