### ISSUE TITLE
Infospot onClick to another pano?

### ISSUE THREAD

**Issue by LouGriffith** [pchen66/panolens.js#75]
Hi, 

I am having difficulty with setting the onClick event on a infoSpot. What I am looking for is a way to link a infoSpot to another pano. 

I wanted to have more control on the positioning of the infospot than using the pano linking. 

Is this something you can help with? I appreciate you assistance yesterday.

**Comment by LouGriffith** [comment]
This is what I have ... 

`infospotInfo = new PANOLENS.Infospot( 1000, 'images/sj-icon-abc-info.png' );
infospotInfo.position.set( 1947.96, -100.91, 4519.40 );
infospotInfo.addHoverText( 'The Story' );
// infospotInfo.onClick(viewer.add( abcultra ));
infospotInfo.addEventListener( 'click', function(){ window.location.href = "sj-abc-info.html"; });
abcfar.add( infospotInfo );`

This works going page to page. What I am hoping is to link to another pano via the infoSpot.

**Comment by pchen66** [comment]
So I'm not sure if I understand correctly. Are you looking for something like this [Custom Linking](https://codepen.io/pchen66/pen/yXeWMJ) ? 

If you want to manually set a panorama, you can do
```
viewer.setPanorama( ANOTHER_PANORAMA );
```

**Comment by LouGriffith** [comment]
Perfect! That's what I was looking for. Works perfectly! Appreciate your help! 
`infospotUltra.addEventListener( 'click', function(){ viewer.setPanorama( abcultra ); });
`
