### ISSUE TITLE
Black screen in-between panoramas

### ISSUE THREAD

**Issue by gerwin3** [pchen66/panolens.js#78]
When using `setPanorama`, by default, a black screen is visible while the new panorama is loading. I've already implemented a custom loading screen that displays a loading animation while this is happening. To enhance the experience I'd like to get rid of the black screen in-between panorama's. Is there an easy way to do it?

**Comment by pchen66** [comment]
When calling `setPanorama`, the current panorama is calling `onLeave` method while the target panorama calls for `onEnter`. By default there's a transition which takes leaving panorama's opacity from 1 to 0 and entering panorama's opacity from 0 to 1. The black screen you see is when opacity comes to 0. 

So in your case, do you want to disable the default transition completely? A quick way to do this is set the animation duration on the panorama you want to set.
```
panorama.animationDuration = 0;
```

**Comment by donblaauw** [comment]
So in theory one could make a cross dissolve by setting the new panorama underneath the one that transitions into opacity 0?

**Comment by pchen66** [comment]
@donblaauw Yes, cross fade / dissolve effect can be implemented with custom `setPanorama` method

**Comment by gerwin3** [comment]
I can get the cross fade effect to work on setPanorama by removing the delay on the fade-in animation, but it only works correctly if the target panorama is already loaded. If not, the black screen still appears. Any idea how to implement this so it also works on panorama's that aren't loaded yet?

**Comment by gerwin3** [comment]
I don't even necessarily need the cross fade, a sudden transition would also work, as long as no black screen is visible. Thanks for your help!

**Comment by pchen66** [comment]
@gerwin3 There are additional parameters can be passed in with `setPanorama` in the `dev` branch, which indicates whether to disable leaving / entering transitions. Please take a look at this [example](https://codepen.io/pchen66/pen/RgxeJM/). 

When clicking on panorama1 button, it would disable both default transitions. Button 2 is to keep entering transition but disable leaving one. Button 3 is the default. Let me know if that's what you're looking for.

**Comment by gerwin3** [comment]
@pchen66 That fixes the black screen for transitions between two scenes that have already loaded before. But when you call setPanorama(X) and X is not loaded (via X.load() - which is called in the onEnter implementation of Panorama when the scene wasn't loaded before), then a black screen still appears in-between the two panoramas. In your demo the images aren't large enough to notice the delay, but some of the images I use in my project are 5MB and the delay becomes significant. Is there a way to delay the fadeOut of the previous panorama until the next one is fully loaded?

**Comment by pchen66** [comment]
Since r8 revision it's default to `onLeave` only after the next panorama is loaded with basic cross fade support. [Set Panorama Maunally Example](https://codepen.io/pchen66/pen/RgxeJM) would show this behavior without in-between black screen. The 3rd panorama is 9.5MB. No more additional parameter for `setPanorama` to simplify API usage.

**Comment by gerwin3** [comment]
That's exactly what I needed! Thanks!
