### ISSUE TITLE
How can you make a resize of the container or canvas?

### ISSUE THREAD

**Issue by SoyAndresHernandez** [pchen66/panolens.js#80]
Hi
I could make the canvas rewrite again to fit the screen. I've tried this.

`window.addEventListener('resize', function() {
      console.log(viewer);
      viewer.HANDLER_WINDOW_RESIZE();
    });`

But I did not work, somebody could help me. Thank you so much.

**Comment by pchen66** [comment]
Can you elaborate when / what you need to resize the screen? A [codepen example like this](https://codepen.io/pchen66/pen/gMmggW) would be helpful to determine the issue.

**Comment by pchen66** [comment]
Here's an example with dynamic container size [Container Example](https://codepen.io/pchen66/pen/gMmggW). By default there's no resize event attached to DOM element, only to `window`, but you can build your own resize listener and call `viewer.onWindowResize( width, height )` whenever you detect the size is being changed.
