### ISSUE TITLE
Add new button

### ISSUE THREAD

**Issue by CesarBalzer** [pchen66/panolens.js#81]
I would like to know how to add a new control button next to the existing ones in VideoPanorama, I can not understand how to put this, if they can help I'll be grateful

**Comment by pchen66** [comment]
Here's an example for custom control item on existing control bar. They can be specified as video group only. [Custom Widget](https://codepen.io/pchen66/pen/vZVyYr)

**Comment by CesarBalzer** [comment]
Thank you very much, that's what I needed to know about buttons.
