### ISSUE TITLE
Adding a DomElement in infospot

### ISSUE THREAD

**Issue by sankar254** [pchen66/panolens.js#88]
Is there a way to add an infospot with DomElement instead of using an image.

**Comment by pchen66** [comment]
Not currently. However, you can have a workaround by hiding infospot and overlay dom elements together with `viewer.getScreenVector` to achieve such effect. The hoverElement in [Infospot](https://pchen66.github.io/Panolens/examples/panorama_infospot.html) example is taking the same approach behind the scene.

**Comment by Burans** [comment]
@pchen66 I'm having a hard time getting the `viewer.getScreenVector` to work. Could you maybe explain it a bit more? I'm trying to attach custom DOM elements to the infospots but they are mirrored in a weird way. The red dots should be on top of the white ones in the image I have added. 

Also - how to deal with the problem that the DOM elements are also mirrored by 180 degrees and are also visible while they should be behind the camera?

My approach currently:

```javascript
for (let i = 0; i < domInfoSpots.length; i++) {
  let vec = infoSpots[i].position;

  let x = viewer.getScreenVector(vec).x;
  let y = viewer.getScreenVector(vec).y;
  
  domInfoSpots[i].style.transform = 'translate(' + x + 'px,' + y + 'px)';
}
```
<img width="668" alt="screen shot 2018-07-15 at 01 41 49" src="https://user-images.githubusercontent.com/3708660/42728943-5bf78454-87d0-11e8-8316-f4833f10d861.png">

Thanks a lot for the great library!

**Comment by dgintis** [comment]
@pchen66, can you elaborate a little on this? I'm unclear on how to get proper x/y coordinates for the DOM element I'd like to position where the infospot is. `viewer.getScreenVector(infospot)` returns x/y coordinates, but they do not seem to correspond with the actual position of the infospot within the viewport.

Thanks for your help!!
