### ISSUE TITLE
How do I update the picture?

### ISSUE THREAD

**Issue by dan-me** [pchen66/panolens.js#90]
e.g:
```
var panorama, viewer;
panorama = new PANOLENS.ImagePanorama( 'asset/equirectangular.jpg' );
viewer = new PANOLENS.Viewer();
viewer.add( panorama );
```
How do I update  'asset/equirectangular.jpg'' ?

**Comment by matthewgovaere** [comment]
I was able to achieve this by using the `setPanorama` method on the viewer.

So, for example, if you wanted to remove the old panorama and replace it with a new one...

```
viewer.remove( panorama );

newpanorama = new PANOLENS.ImagePanorama( 'asset/equirectangular2.jpg' );

viewer.add( newpanorama );
viewer.setPanorama( newpanorama );
```

**Comment by dan-me** [comment]
@matthewgovaere  thank you very much！   😘

**Comment by pchen66** [comment]
Besides @matthewgovaere pointed out using two panoramas (which is good if you want to have cross-fade effect), you can also update the texture directly in the same panorama. Take a look at this example: [Image Panorama - Update Image](https://codepen.io/pchen66/pen/YxeYGZ). The idea behind is to update texture of this panorama's material. 
```
panorama.material.map = NEW_TEXUTRE;
```

**Comment by MuhammedMetwaly** [comment]
Ihave tried the setPanorama method but it didnt work.

You can also use dispose() method first
then use the add() method again
