### ISSUE TITLE
How create separate controls buttons

### ISSUE THREAD

**Issue by CesarBalzer** [pchen66/panolens.js#91]
I would like to know how to create the separate buttons and how to call the events of the default control, show me one example please. 
Or for example, I wanted you to start the video without the control bar, and I could set to start the video in touch mode.
Tnx

**Comment by pchen66** [comment]
Take a look at this example: [Control Externally](https://codepen.io/pchen66/pen/dmmGKM). It shows without activating the default control button it can still access it's functionality.
