### ISSUE TITLE
Dynamic InfoSpots

### ISSUE THREAD

**Issue by Rus-Cosmin** [pchen66/panolens.js#92]
Is there a way to add InfoSpots after the view is 'rendered'?I tried too add them after i added the panorama to the view but they were not visible/rendered(the info spots were added to the panorama object from what i've seen in console) 

'Fix': When the infospot was created it sets the display to none and the viewer had autohideInfospots to false so the infospot was not visible. To fix that i made again all hotspots visible : `panorama.toggleInfospotVisibility(true);`

**Comment by lucychen0103** [comment]
@Rus-Cosmin Hi! Where did you put panorama.toggleInfospotVisibility(true)?
