### ISSUE TITLE
Popular smartphone Huawai P8 Android 6.0 makes the panorama's jitter a lot when set to sensor.

### ISSUE THREAD

**Issue by donblaauw** [pchen66/panolens.js#93]
Also left an right aren't really working..
I know the smartphone is a budget phone and the gyro isn't that swell,
but did you know of this issue? or by other devices?

Is it up to the manufacturer to update something? update to android 8 isn.t possible it seems.

**Comment by pchen66** [comment]
yeah, this was a known issue regarding older generation phones with noisy gyro information. It was also dependent on browser interpretation of sensor information. It won't be reliably solved from js library's perspective.
