### ISSUE TITLE
'Fixed' HTML element on image panorama

### ISSUE THREAD

**Issue by Rus-Cosmin** [pchen66/panolens.js#94]
Is there a way to place an html element at a certain position(infospot position) ?Like instead on infospot icon to be a html element or to show hover element at position 0 and to destroy hover event?

**Comment by abislah** [comment]
did you find a solution for this? i want to do the same thing.

**Comment by claytonrothschild** [comment]
Any luck on this @Rus-Cosmin, @abislah ?

**Comment by Rus-Cosmin** [comment]
I modified the code a little and it seems to partially work. But on the 'dual screen' mode it has a lot of bugs and the elements don't hide. Frankly it's a mess on 'dual screen'

**Comment by flyandi** [comment]
Marking this as stale as it's older than 6  months. Subject to be deleted.
