### ISSUE TITLE
Bootstrap infospot offset issue

### ISSUE THREAD

**Issue by garymould** [pchen66/panolens.js#97]
This is a great script!

I cannot get the 'custom container' method to work with Bootstrap without adding offsets to the infospot hit areas. The mouse is offset by the space above and to the left of the canvas. I have created a codepen to demonstrate the issue:

https://codepen.io/Vibegaz/pen/MvdEeR

I have managed to make the iframe method work responsively, but I need to have external buttons as shown in my example.

Any help would be most appreciated.

**Comment by garymould** [comment]
This image demonstrates the offset:
![panolens-offset](https://user-images.githubusercontent.com/20706470/30157290-cf14bad0-93b9-11e7-95b5-1482ee69c087.jpg)

**Comment by lesitevideo** [comment]
this seems a raycasting offset problem with threejs, because of the canvas : does this thread help you ?
https://stackoverflow.com/questions/13542175/three-js-ray-intersect-fails-by-adding-div/13544277#13544277

**Comment by garymould** [comment]
I managed to solve the issue using an iframe with external controls after all:
https://codepen.io/Vibegaz/pen/YEXWXV

This will only work if both the container and iframe reside on the same domain.

**Comment by garymould** [comment]
Here's a link to the iframe content: https://codepen.io/Vibegaz/pen/aVOZJZ
