### ISSUE TITLE
Stereoscopic mode for viewing for two images simultaneously?

### ISSUE THREAD

**Issue by seanwittmeyer** [pchen66/panolens.js#98]
Panolens has been great for viewing a single image in a scene but can it load a second image for cardboard/stereoscopic mode for when you have separate images for each eye? I create rendered cube maps and equirectangular panoramas for viewing that have slightly different content for each eye to help give depth to scenes and we want to enhance the views we have already with panolens. Is this possible? We were using twgl.js but the simplicity and speed of panolens makes it a more flexible and compelling platform.

Ideally, panolens would load a single and present image (l.jpg as an example) as it does now then load (r.jps) in the background for use when the user enables the cardboard or stereo mode. Use with either or both CubePanorama and ImagePanorama would be great.

**Comment by donblaauw** [comment]
This would be a Great addition indeed 😄

**Comment by ricmob** [comment]
Or taking a top-bottom (stereoscopic) equirectangular 3D 360 image and using the top half for the left eye and the bottom for the right eye.
